import type { Difficulty } from "../types";

export const CSS_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "color: red;",
    "font-size: 16px;",
    "margin: 0 auto;",
    "display: flex;",
    "background: #fff;",
    "padding: 1rem;",
    "border-radius: 8px;",
    "text-align: center;",
    "width: 100%;",
    "opacity: 0.5;",
    "cursor: pointer;",
    "font-weight: bold;",
    "line-height: 1.5;",
    "border: none;",
    "outline: none;",
    "height: auto;",
    "max-width: 100%;",
    "position: relative;",
    "z-index: 10;",
    "float: left;",
    "clear: both;",
    "visibility: hidden;",
    "pointer-events: none;",
    "white-space: nowrap;",
    "list-style: none;",
    "text-transform: uppercase;",
    "letter-spacing: 1px;",
    "word-break: break-all;",
    "user-select: none;",
    "vertical-align: middle;",
    "box-sizing: border-box;",
    "overflow: hidden;",
    "text-decoration: none;",
    "font-style: italic;",
    "flex-direction: column;",
    "justify-content: center;",
    "align-items: center;",
    "flex-wrap: wrap;",
    "gap: 10px;",
    "order: 1;",
    "flex-grow: 1;",
    "object-fit: cover;",
    "resize: none;",
    "aspect-ratio: 16 / 9;",
    "scroll-behavior: smooth;",
    "mix-blend-mode: multiply;",
    "accent-color: #6366f1;",
    "caret-color: red;",
    "all: unset;",
    "right: 0;",
    "bottom: 0;",
    "top: 10px;",
    "left: -5px;",
    "font-size: 14px;",
    "font-family: inherit;",
    "text-transform: lowercase;",
    "font-weight: 500;",
    "min-height: 100vh;",
    "display: block;",
    "display: inline-block;",
    "overflow-x: auto;",
    "overflow-y: scroll;",
    "border-style: dashed;",
    "border-width: 2px;",
    "border-color: #ccc;",
    "background-color: transparent;",
    "box-shadow: none;",
    "transition: none;",
    "content: none;",
    "list-style-type: square;",
    "text-indent: 2em;",
    "word-spacing: 2px;",
    "white-space: normal;",
    "text-overflow: clip;",
    "direction: rtl;",
    "writing-mode: vertical-lr;",
    "caption-side: bottom;",
    "empty-cells: hide;",
    "table-layout: fixed;",
    "border-collapse: collapse;",
    "border-spacing: 0;",
    "color: #333;",
    "color: inherit;",
    "color: currentColor;",
    "background: red;",
    "background-size: cover;",
    "background-position: center;",
    "margin: 0;",
    "margin-top: 8px;",
    "margin-bottom: 16px;",
    "padding: 0;",
    "padding-top: 1rem;",
    "padding-left: 2rem;",
    "width: auto;",
    "height: 100%;",
    "min-width: 0;",
    "max-height: 100vh;",
    "display: inline;",
    "display: none;",
    "visibility: visible;",
    "opacity: 1;",
    "font-size: 1rem;",
    "font-size: 0.875rem;",
    "font-weight: 400;",
    "font-weight: 700;",
    "line-height: 1.25;",
    "text-align: left;",
    "text-align: right;",
    "text-decoration: underline;",
    "text-transform: capitalize;",
    "letter-spacing: 0.05em;",
    "word-wrap: break-word;",
    "overflow: visible;",
    "overflow: scroll;",
    "position: static;",
    "position: fixed;",
    "position: sticky;",
    "top: 0;",
    "left: 0;",
    "right: auto;",
    "z-index: 1;",
    "z-index: 50;",
    "float: none;",
    "clear: left;",
    "box-sizing: content-box;",
    "border: 1px solid #000;",
    "border-radius: 4px;",
    "border-top: none;",
    "outline: 2px solid blue;",
    "box-shadow: 0 1px 2px rgba(0,0,0,0.1);",
    "cursor: default;",
    "cursor: not-allowed;",
    "user-select: text;",
    "pointer-events: auto;",
    "resize: both;",
    "object-fit: contain;",
    "object-position: center;",
    "list-style: disc;",
    "list-style-position: inside;",
    "vertical-align: top;",
    "white-space: pre;",
    "flex: 1;",
    "flex-shrink: 1;",
    "flex-basis: auto;",
    "align-self: center;",
    "justify-self: start;",
    "gap: 8px;",
    "row-gap: 12px;",
    "column-gap: 16px;",
    "order: 0;",
    "flex-direction: row;",
    "align-content: center;",
    "place-content: start;",
    "grid-template-columns: 1fr;",
    "grid-template-rows: auto;",
    "grid-column: 1;",
    "grid-row: 1;",
    "aspect-ratio: 1;",
    "scroll-behavior: auto;",
    "scroll-snap-type: none;",
    "isolation: auto;",
    "mix-blend-mode: normal;",
    "filter: none;",
    "transform: none;",
    "transition: 0.2s;",
    "animation: none;",
    "content: normal;",
    "quotes: none;",
    "tab-size: 4;",
    "hyphens: none;",
    "min-height: 0;",
    "max-width: none;",
    "min-width: 100px;",
    "block-size: auto;",
    "inline-size: 50%;",
    "margin-inline: auto;",
    "padding-block: 0.5rem;",
    "inset: auto;",
    "color-scheme: dark;",
    "print-color-adjust: exact;",
    "text-rendering: optimizeLegibility;",
    "font-synthesis: none;",
    "text-size-adjust: 100%;",
    "touch-action: auto;",
    "overscroll-behavior: auto;",
  ],
  medium: [
    "display: flex; align-items: center; justify-content: space-between;",
    "background-color: rgba(0, 0, 0, 0.5);",
    "transition: all 0.3s ease-in-out;",
    "box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);",
    "grid-template-columns: repeat(3, 1fr);",
    "border: 1px solid #e2e8f0;",
    "font-family: 'Inter', sans-serif;",
    "transform: translateX(-50%) translateY(-50%);",
    "overflow: hidden; text-overflow: ellipsis; white-space: nowrap;",
    "position: absolute; top: 50%; left: 50%;",
    "display: grid; gap: 1rem; padding: 1.5rem;",
    "max-width: 1200px; margin: 0 auto; padding: 0 1rem;",
    "border-radius: 12px; padding: 16px 24px;",
    "animation: fadeIn 0.3s ease forwards;",
    "backdrop-filter: blur(12px); background: rgba(255,255,255,0.05);",
    "background: linear-gradient(to right, #ff007f, #7f00ff);",
    "box-shadow: inset 0 2px 4px 0 rgba(0, 0, 0, 0.06);",
    "filter: blur(4px) grayscale(50%);",
    "transform: scale(1.05) rotate(5deg);",
    "grid-column: span 2 / span 2;",
    "place-items: center; place-content: center;",
    "flex: 1 1 calc(33.333% - 20px);",
    "font-size: clamp(1rem, 2.5vw, 2rem);",
    "border-image: linear-gradient(to right, red, blue) 1;",
    "will-change: transform, opacity;",
    "scroll-snap-type: x mandatory;",
    "scroll-snap-align: center;",
    "overscroll-behavior: contain;",
    "column-count: 3; column-gap: 1.5rem;",
    "shape-outside: circle(50%); float: left;",
    "text-shadow: 1px 1px 2px black, 0 0 1em blue;",
    "content: ''; display: table; clear: both;",
    "box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1);",
    "isolation: isolate; z-index: 1;",
    "stroke: currentColor; stroke-width: 2;",
    "fill: transparent; transition: fill 0.2s;",
    "background-clip: text; -webkit-background-clip: text;",
    "transform-style: preserve-3d; perspective: 1000px;",
    "touch-action: manipulation; -webkit-tap-highlight-color: transparent;",
    "grid-template-rows: auto 1fr auto;",
    "counter-increment: section; content: counter(section) '. ';",
    "scroll-padding-top: 5rem; scroll-margin-top: 2rem;",
    "grid-auto-flow: row dense; grid-auto-rows: minmax(100px, auto);",
    "background-size: contain; background-repeat: no-repeat; background-position: center;",
    "object-position: center top; image-rendering: pixelated;",
    "text-decoration-line: underline; text-decoration-style: wavy; text-decoration-color: red;",
    "text-underline-offset: 4px; text-emphasis: circle #a855f7;",
    "clip-path: circle(50% at 50% 50%); margin-inline: auto;",
    "padding-block: 2rem 1.5rem; inset-inline-start: 0;",
    "inline-size: 100%; block-size: max-content;",
    "contain: paint layout; content-visibility: auto;",
    "hyphenate-character: '-'; text-orientation: mixed;",
    "line-break: strict; overflow-wrap: break-word;",
    "font-variant-numeric: tabular-nums lining-nums;",
    "font-feature-settings: 'pnum' on, 'lnum' on;",
    "scrollbar-gutter: stable; interpolate-size: allow-keywords;",
    "display: flex; flex-direction: row; gap: 1rem;",
    "display: grid; grid-template-columns: repeat(2, 1fr);",
    "margin: 1rem 2rem; padding: 0.5rem 1rem;",
    "font: 500 1rem/1.5 system-ui, sans-serif;",
    "background: linear-gradient(180deg, #fff, #eee);",
    "border: 2px solid var(--border, #ccc);",
    "border-radius: 0.5rem 1rem;",
    "box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);",
    "transform: translateY(-2px);",
    "transform: rotate(45deg);",
    "filter: blur(2px);",
    "transition: color 0.2s, background 0.2s;",
    "animation: slide 0.4s ease-out;",
    "overflow: hidden; text-overflow: ellipsis;",
    "white-space: nowrap; max-width: 20ch;",
    "position: relative; z-index: 2;",
    "inset: 0;",
    "width: min(100%, 640px);",
    "height: clamp(200px, 40vh, 600px);",
    "aspect-ratio: 16/9; object-fit: cover;",
    "grid-auto-flow: column; grid-auto-columns: 120px;",
    "flex: 1 1 200px; align-items: stretch;",
    "justify-content: flex-end; place-items: end;",
    "scroll-snap-type: y proximity;",
    "overscroll-behavior: auto;",
    "touch-action: pan-x;",
    "user-select: all;",
    "caret-color: auto;",
    "accent-color: auto;",
    "color-scheme: light dark;",
    "contain: layout style;",
    "content-visibility: hidden;",
    "will-change: auto;",
    "mask-size: cover;",
    "clip-path: inset(0);",
    "shape-margin: 1rem;",
    "column-width: 200px;",
    "break-inside: avoid;",
    "orphans: 3; widows: 3;",
    "text-indent: 1em hanging;",
    "word-spacing: 0.25em;",
    "letter-spacing: 0.1em;",
    "font-variant: small-caps;",
    "font-stretch: condensed;",
    "text-decoration-thickness: 2px;",
    "outline-offset: 2px;",
    "border-inline: 1px solid;",
    "margin-block: 1rem;",
    "padding-inline: 1.5rem;",
    "inset-block: 0;",
    "block-size: auto; inline-size: 100%;",
    "display: flex; flex-wrap: wrap; align-items: flex-start;",
    "grid-template: 'a b' 'c d' / 1fr 1fr;",
    "background: color-mix(in srgb, #111 80%, transparent);",
    "border: 1px solid color-mix(in oklab, canvasText 15%, transparent);",
  ],
  hard: [
    "@media (max-width: 768px) { .container { flex-direction: column; } }",
    ":root { --primary: #6366f1; --secondary: #8b5cf6; --radius: 0.5rem; }",
    ".card:hover { transform: translateY(-4px); box-shadow: 0 20px 40px rgba(0,0,0,0.15); }",
    "background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);",
    "@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; } }",
    ".btn::before { content: ''; position: absolute; inset: 0; border-radius: inherit; }",
    "grid-template-areas: 'header header' 'sidebar main' 'footer footer';",
    "clip-path: polygon(0 0, 100% 0, 100% 85%, 0 100%);",
    "animation: spin 1s linear infinite; transform-origin: center center;",
    "filter: drop-shadow(0 0 8px rgba(99, 102, 241, 0.6));",
    "@supports (display: grid) { .layout { display: grid; } }",
    ".item:nth-child(odd) { background: rgba(255,255,255,0.03); }",
    "content: attr(data-tooltip); position: absolute; bottom: 100%;",
    "scrollbar-width: thin; scrollbar-color: #6366f1 transparent;",
    "mask-image: linear-gradient(to bottom, black 60%, transparent 100%);",
    "grid-template-columns: minmax(200px, 1fr) minmax(auto, 80ch);",
    "background: radial-gradient(circle at top right, #333, #000 80%);",
    "input[type='text']:focus:not([disabled]) { border-color: #6366f1; }",
    "span::after { content: counter(item); counter-increment: item; }",
    "transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0deg);",
    "@media (prefers-color-scheme: dark) { body { background-color: #121212; } }",
    "box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.5), 0 4px 6px -1px rgba(0, 0, 0, 0.1);",
    "transition: transform 0.6s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.6s;",
    "div:not(:last-child)::after { content: '|'; padding: 0 0.5rem; }",
    "background-image: repeating-linear-gradient(45deg, transparent, transparent 10px, #fff 10px);",
    "filter: contrast(200%) brightness(150%) saturate(120%);",
    "offset-path: path('M 10 80 C 40 10, 60 10, 90 80'); animation: move 5s linear infinite;",
    "column-rule: 1px dashed rgba(255, 255, 255, 0.12);",
    "mask: radial-gradient(circle at 50% 50%, transparent 40%, black 41%);",
    "text-decoration: underline wavy rgba(239, 68, 68, 0.8) 2px;",
    "grid-row-start: line2; grid-row-end: 5; grid-column-start: col-start;",
    "overscroll-behavior-y: contain; -webkit-overflow-scrolling: touch;",
    "@container sidebar (width > 400px) { .card { display: flex; } }",
    "image-rendering: -webkit-optimize-contrast; image-rendering: crisp-edges;",
    "backdrop-filter: saturate(180%) blur(20px); background-color: rgba(0,0,0,0.7);",
    "content: '\\2192'; margin-left: 0.5em; font-family: sans-serif;",
    "clip-path: ellipse(25% 40% at 50% 50%);",
    "animation: shake 0.5s cubic-bezier(.36,.07,.19,.97) both;",
    "hyphens: auto; text-justify: inter-word; text-align: justify;",
    "mix-blend-mode: color-dodge; pointer-events: none; will-change: filter;",
    "position: absolute; position-anchor: --my-anchor; top: anchor(bottom);",
    "width: calc(100% - max(2rem, 20px)); padding: max(1rem, min(2vw, 3rem));",
    "grid-template-columns: repeat(auto-fit, minmax(clamp(200px, 50%, 400px), 1fr));",
    "background-image: conic-gradient(from 180deg at 50% 50%, #111, #444, #111);",
    "transform: perspective(500px) rotateX(25deg) translateZ(10px);",
    "box-shadow: 0px 0px 20px 5px var(--glow-color, rgba(255,255,255,0.2));",
    "ul > li:nth-last-child(-n+3):has(a[href^='https']) { font-weight: 600; }",
    "p:has(+ h2), li:not(.active):color-mix(in srgb, var(--primary) 30%, transparent) { color: red; }",
    "anchor-name: --popover-anchor; position-visibility: always; view-timeline-name: --revealing;",
    "animation-timeline: --revealing; animation-range: entry 10% exit 90%;",
    "outline: 2px solid light-mix(in oklab, canvas, canvasText 50%);",
    "container-type: inline-size; container-name: main-feed-container;",
    "@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: .5; } }",
    "path:nth-of-type(3n+1) { fill: var(--accent-color); stroke-dasharray: 5, 5; }",
    "@media (min-width: 1024px) { .sidebar { width: 280px; } }",
    "@media (hover: hover) { .btn:hover { opacity: 0.9; } }",
    "@media (prefers-reduced-motion: reduce) { * { animation: none !important; } }",
    ":is(h1, h2, h3):where(:not([class])) { margin-block: 0 0.5em; }",
    ":where(ul, ol) { padding-inline-start: 1.5rem; }",
    ".grid > *:nth-child(3n) { grid-column: span 2; }",
    "a[href^='https://']::after { content: ' ↗'; font-size: 0.85em; }",
    "input:user-invalid { border-color: #ef4444; }",
    "::placeholder { color: #9ca3af; opacity: 1; }",
    "@layer reset, base, components, utilities;",
    "@layer components { .card { padding: 1rem; border-radius: 0.75rem; } }",
    "@property --angle { syntax: '<angle>'; inherits: false; initial-value: 0deg; }",
    "background: conic-gradient(from var(--angle), red, yellow, lime, aqua, blue, magenta, red);",
    "animation: spin 4s linear infinite; @keyframes spin { to { --angle: 360deg; } }",
    "grid-template-columns: subgrid; grid-column: 1 / -1;",
    "container-type: size; @container (min-height: 400px) { .hero { min-height: 50cqh; } }",
    "view-transition-name: hero-image; ::view-transition-old(hero-image) { animation: fade-out 0.3s; }",
    "scroll-timeline: --section-scroll y; animation-timeline: --section-scroll;",
    "position: fixed; position-area: block-end span-inline-end;",
    "color: color-mix(in oklch, var(--fg) 85%, var(--bg));",
    "background-color: light-dark(#fff, #111);",
    "border-color: color-mix(in srgb, canvasText 20%, transparent);",
    "filter: url(#noise) contrast(120%);",
    "clip-path: path('M0,0 H100 V100 Z');",
    "mask-composite: intersect; mask-mode: alpha;",
    "shape-outside: margin-box;",
    "text-wrap: balance; text-wrap: pretty;",
    "initial-letter: 3 2;",
    "font-variation-settings: 'wght' 650, 'opsz' 32;",
    "font-optical-sizing: auto;",
    "text-decoration: underline dotted from-font;",
    "hyphenate-limit-chars: 6 3 2;",
    "overflow: clip; scrollbar-gutter: stable both-edges;",
    "overscroll-behavior-block: contain;",
    "scroll-margin-block: 4rem;",
    ":has(> img) { display: grid; place-items: center; }",
    ":not(.skip-link):focus-visible { outline: 2px solid Highlight;",
    "@starting-style { .panel { opacity: 0; transform: translateY(8px); } }",
    ".panel { transition: opacity 0.3s, transform 0.3s; @starting-style { opacity: 0; } }",
  ],
};
