import type { Difficulty } from "../types";

export const EXPRESS_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "const express = require('express')",
    "import express from 'express'",
    "const app = express()",
    "const router = express.Router()",
    "app.listen(3000)",
    "app.listen(PORT)",
    "app.get('/')",
    "app.post('/')",
    "app.put('/:id')",
    "app.patch('/:id')",
    "app.delete('/:id')",
    "router.get('/')",
    "router.use(middleware)",
    "app.use(express.json())",
    "app.use(express.urlencoded())",
    "app.use(cors())",
    "app.use(helmet())",
    "app.use(morgan('dev'))",
    "app.use('/api', router)",
    "app.use(express.static('public'))",
    "req.body",
    "req.params",
    "req.query",
    "req.headers",
    "req.cookies",
    "req.method",
    "req.path",
    "req.ip",
    "req.hostname",
    "res.send('ok')",
    "res.json({})",
    "res.status(200)",
    "res.status(404)",
    "res.status(500)",
    "res.redirect('/')",
    "res.sendFile(path)",
    "res.set('Header', 'val')",
    "res.cookie('token', val)",
    "res.clearCookie('token')",
    "res.end()",
    "next()",
    "next(err)",
    "return res.json({})",
    "module.exports = app",
    "export default app",
    "export default router",
    "const PORT = 3000",
    "process.env.PORT",
    "process.env.NODE_ENV",
    "console.log('listening')",
    "app.get('/health', (req, res) => {})",
    "app.post('/login', (req, res) => {})",
    "(req, res) => {}",
    "(req, res, next) => {}",
    "function handler(req, res) {}",
    "async (req, res) => {}",
    "try {}",
    "catch (err) {}",
    "throw err",
    "if (!user) return res.status(401).send()",
    "const { id } = req.params",
    "const { q } = req.query",
    "const token = req.header('Authorization')",
    "res.locals.user",
    "app.set('view engine', 'ejs')",
    "res.render('index')",
    "app.disable('x-powered-by')",
    "app.enable('trust proxy')",
    "express.json({ limit: '1mb' })",
    "express.raw({ type: 'application/json' })",
    "express.text()",
    "express.static('dist')",
    "path.join(__dirname, 'files')",
    "fs.readFileSync(path)",
    "require('dotenv').config()",
    "import 'dotenv/config'",
    "const cors = require('cors')",
    "app.use(cors({ origin: true }))",
    "bcrypt.hash(pw, 10)",
    "bcrypt.compare(pw, hash)",
    "jwt.sign(payload, secret)",
    "jwt.verify(token, secret)",
    "app.get('/api/health', (req, res) => res.json({ ok: true }));",
    "app.use(express.json());",
    "const { id } = req.params;",
    "res.status(404).json({ error: 'Not found' });",
    "next();",
    "app.get('/users', listUsers)",
    "app.post('/users', createUser)",
    "app.put('/users/:id', updateUser)",
    "app.patch('/users/:id', patchUser)",
    "app.delete('/users/:id', removeUser)",
    "app.head('/health', handler)",
    "app.options('*', cors())",
    "router.get('/me', getMe)",
    "req.query.page",
    "req.query.limit",
    "req.params.slug",
    "req.body.email",
    "req.cookies.sid",
    "req.signedCookies.user",
    "req.ip",
    "req.ips",
    "req.hostname",
    "req.protocol",
    "req.secure",
    "req.xhr",
    "req.path",
    "req.baseUrl",
    "req.originalUrl",
    "res.sendStatus(200)",
    "res.json({ data })",
    "res.status(201).send({ id })",
    "res.redirect(302, '/login')",
    "res.render('index', { title: 'Home' })",
    "res.setHeader('Cache-Control', 'no-store')",
    "res.append('Set-Cookie', 'a=1')",
    "res.locals.user = user",
    "next('route')",
    "next(err)",
    "express.static('public')",
    "express.json({ limit: '2mb' })",
    "express.urlencoded({ extended: true })",
    "express.Router({ mergeParams: true })",
    "app.use(morgan('combined'))",
    "app.use(cors({ origin: process.env.CLIENT_URL }))",
    "app.use(helmet())",
    "app.use(compression())",
    "app.use(cookieParser(secret))",
    "app.disable('x-powered-by')",
  ],
  medium: [
    "import express, { Request, Response, NextFunction } from 'express'",
    "app.use((req, res, next) => { next() })",
    "const auth = (req, res, next) => { if (!req.user) return res.sendStatus(401); next() }",
    "router.param('id', (req, res, next, id) => { req.id = id; next() })",
    "app.route('/book').get(list).post(create)",
    "app.all('/secret', handler)",
    "res.status(201).json({ id: doc.id })",
    "res.status(400).json({ error: 'Invalid' })",
    "res.sendStatus(204)",
    "res.type('json')",
    "res.format({ json: () => res.json({}), html: () => res.send('<p/>') })",
    "res.download(file, 'name.pdf')",
    "res.attachment('report.csv')",
    "res.links({ next: '/page/2' })",
    "res.vary('Accept')",
    "req.accepts('json')",
    "req.is('application/json')",
    "req.get('Content-Type')",
    "req.range(1000)",
    "app.use('/users/:userId/posts', postsRouter)",
    "router.use('/:postId/comments', commentsRouter)",
    "express.Router({ mergeParams: true })",
    "app.use((err, req, res, next) => { console.error(err); res.status(500).json({ message: err.message }) })",
    "const asyncHandler = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next)",
    "app.get('/items', asyncHandler(async (req, res) => { const items = await db.all(); res.json(items) }))",
    "import rateLimit from 'express-rate-limit'",
    "const limiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100 })",
    "app.use('/api/', limiter)",
    "import compression from 'compression'",
    "app.use(compression())",
    "import session from 'express-session'",
    "app.use(session({ secret: process.env.SESSION_SECRET, resave: false, saveUninitialized: false }))",
    "import cookieParser from 'cookie-parser'",
    "app.use(cookieParser())",
    "import multer from 'multer'",
    "const upload = multer({ dest: 'uploads/' })",
    "app.post('/upload', upload.single('file'), handler)",
    "import { body, validationResult } from 'express-validator'",
    "app.post('/user', body('email').isEmail(), (req, res) => { const errors = validationResult(req) })",
    "import mongoose from 'mongoose'",
    "mongoose.connect(process.env.MONGO_URI)",
    "const User = mongoose.model('User', schema)",
    "import { PrismaClient } from '@prisma/client'",
    "const prisma = new PrismaClient()",
    "await prisma.user.findMany({ where: { active: true } })",
    "import Redis from 'ioredis'",
    "const redis = new Redis(process.env.REDIS_URL)",
    "import http from 'http'",
    "const server = http.createServer(app)",
    "import { Server } from 'socket.io'",
    "const io = new Server(server, { cors: { origin: '*' } })",
    "io.on('connection', (socket) => { socket.on('msg', (data) => io.emit('msg', data)) })",
    "server.listen(PORT)",
    "import cluster from 'cluster'",
    "if (cluster.isPrimary) { for (let i = 0; i < cpus; i++) cluster.fork() } else { app.listen(PORT) }",
    "app.use('/api/v1', v1Router)",
    "app.use('/api/v2', v2Router)",
    "router.use(authMiddleware);",
    "app.use('/api/v1', apiRouter);",
    "app.use((err, req, res, next) => { res.status(500).json({ message: err.message }); });",
    "const asyncHandler = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);",
    "app.use('/api', authenticate, apiRouter)",
    "router.param('id', loadById)",
    "app.route('/book').get(getBooks).post(createBook)",
    "app.all('/ping', ping)",
    "res.format({ json: () => res.json({}), html: () => res.send('<p/>') })",
    "res.download(file, 'report.pdf')",
    "res.attachment('data.csv')",
    "res.links({ next: '/p/2' })",
    "req.acceptsCharsets('utf-8')",
    "req.is('multipart/form-data')",
    "req.range(size)",
    "const upload = multer({ storage: multer.memoryStorage() })",
    "app.post('/upload', upload.array('files', 5), done)",
    "import rateLimit from 'express-rate-limit'",
    "app.use(rateLimit({ windowMs: 60000, max: 100 }))",
    "import session from 'express-session'",
    "app.use(session({ secret, resave: false, saveUninitialized: false }))",
    "import { body, validationResult } from 'express-validator'",
    "app.post('/signup', body('email').isEmail(), body('password').isLength({ min: 8 }), validate)",
    "await prisma.user.findUnique({ where: { email } })",
    "await prisma.post.create({ data: { title, authorId } })",
    "mongoose.connect(MONGO_URI)",
    "const doc = await Model.findById(id).lean()",
    "const io = new Server(server)",
    "io.on('connection', (socket) => { socket.on('join', (room) => socket.join(room)) })",
    "server.listen(PORT, () => console.log(PORT))",
    "http.createServer(app)",
  ],
  hard: [
    "import express, { type Request, type Response, type NextFunction, type RequestHandler } from 'express'",
    "interface AuthedRequest extends Request { user: { id: string; role: string } }",
    "const requireRole = (role: string): RequestHandler => (req: AuthedRequest, res, next) => { if (req.user?.role !== role) return res.sendStatus(403); next() }",
    "app.use('/api', authMiddleware, apiRouter)",
    "router.get('/:id', validateId, cache('5 minutes'), async (req, res, next) => { try { const doc = await service.findById(req.params.id); if (!doc) return res.status(404).json({ error: 'Not found' }); res.json(doc) } catch (e) { next(e) } })",
    "const errorHandler: ErrorRequestHandler = (err, req, res, next) => { const status = err.status ?? 500; res.status(status).json({ error: err.message, ...(process.env.NODE_ENV === 'development' && { stack: err.stack }) }) }",
    "app.use((req, res, next) => { req.requestId = crypto.randomUUID(); res.setHeader('X-Request-Id', req.requestId); next() })",
    "import pino from 'pino-http'",
    "app.use(pino({ level: process.env.LOG_LEVEL ?? 'info' }))",
    "import { createProxyMiddleware } from 'http-proxy-middleware'",
    "app.use('/graphql', createProxyMiddleware({ target: 'http://localhost:4000', changeOrigin: true }))",
    "import swaggerUi from 'swagger-ui-express'",
    "app.use('/docs', swaggerUi.serve, swaggerUi.setup(openApiSpec))",
    "import { OpenApiValidator } from 'express-openapi-validator'",
    "app.use(OpenApiValidator.middleware({ apiSpec: './openapi.yaml', validateRequests: true }))",
    "const server = app.listen(PORT, () => logger.info({ port: PORT }, 'ready'))",
    "const shutdown = (signal: string) => { logger.info({ signal }, 'shutting down'); server.close(async () => { await prisma.$disconnect(); process.exit(0) }) }",
    "process.on('SIGTERM', () => shutdown('SIGTERM'))",
    "import { Worker } from 'worker_threads'",
    "app.post('/jobs', async (req, res) => { const job = await queue.add('render', req.body); res.status(202).json({ jobId: job.id }) })",
    "app.get('/jobs/:id', async (req, res) => { const job = await queue.getJob(req.params.id); res.json({ state: await job.getState(), result: job.returnvalue }) })",
    "import passport from 'passport'",
    "import { Strategy as JwtStrategy, ExtractJwt } from 'passport-jwt'",
    "passport.use(new JwtStrategy(opts, async (payload, done) => { const user = await User.findById(payload.sub); done(null, user || false) }))",
    "app.post('/oauth/token', passport.authenticate('local'), (req, res) => { res.json({ token: signToken(req.user) }) })",
    "import { createClient } from 'redis'",
    "const cache = createClient({ url: process.env.REDIS_URL }); await cache.connect()",
    "const cached = await cache.get(key); if (cached) return res.json(JSON.parse(cached))",
    "await cache.setEx(key, 60, JSON.stringify(data))",
    "import { z } from 'zod'",
    "const schema = z.object({ email: z.string().email(), age: z.number().int().positive() })",
    "app.post('/users', (req, res, next) => { const parsed = schema.safeParse(req.body); if (!parsed.success) return res.status(422).json(parsed.error.flatten()); next() })",
    "import { trace, context } from '@opentelemetry/api'",
    "app.use((req, res, next) => { const span = tracer.startSpan(`${req.method} ${req.path}`); context.with(trace.setSpan(context.active(), span), () => { res.on('finish', () => span.end()); next() }) })",
    "export function createApp(deps: Deps) { const app = express(); app.set('trust proxy', 1); app.use(deps.logger); app.use('/api', createApiRouter(deps)); app.use(errorHandler); return app }",
    "if (import.meta.url === `file://${process.argv[1]}`) { const app = createApp(buildDeps()); app.listen(process.env.PORT ?? 3000) }",
    "export function createApp() { const app = express(); app.set('trust proxy', 1); return app; }",
    "app.post('/webhook', express.raw({ type: 'application/json' }), verifySignature, handler);",
    "const requireAuth: RequestHandler = (req, res, next) => { if (!req.user) return res.sendStatus(401); next() }",
    "app.use('/api', requireAuth, apiRouter)",
    "router.get('/:id', cache('1m'), asyncHandler(getOne))",
    "app.use((err: HttpError, req, res, next) => { const status = err.status ?? 500; res.status(status).json({ error: err.message }) })",
    "app.use(pinoHttp())",
    "app.use('/docs', swaggerUi.serve, swaggerUi.setup(spec))",
    "app.use(createProxyMiddleware({ target: 'http://localhost:4000', changeOrigin: true }))",
    "const server = app.listen(PORT); const shutdown = () => server.close(() => process.exit(0)); process.on('SIGTERM', shutdown)",
    "app.post('/stripe/webhook', express.raw({ type: 'application/json' }), stripeWebhook)",
    "const limiter = rateLimit({ keyGenerator: (req) => req.ip ?? 'unknown', standardHeaders: true })",
    "passport.use(new LocalStrategy(async (user, pass, done) => { /* verify */ }))",
    "await redis.setEx(`cache:${key}`, 300, JSON.stringify(payload))",
    "const hit = await redis.get(key)",
  ],
};
