import type { Difficulty } from "../types";

export const HTML_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "<div></div>",
    "<p>Hello</p>",
    "<br>",
    "<hr>",
    "<span>Text</span>",
    "<h1>Title</h1>",
    "<h2>Subtitle</h2>",
    "<ul></ul>",
    "<ol></ol>",
    "<li>Item</li>",
    "<a href=\"#\">Link</a>",
    "<img src=\"\" alt=\"\">",
    "<button>Click</button>",
    "<strong>Bold</strong>",
    "<em>Italic</em>",
    "<b>Bold</b>",
    "<i>Italic</i>",
    "<code>code</code>",
    "<pre></pre>",
    "<table></table>",
    "<tr></tr>",
    "<td>Cell</td>",
    "<th>Head</th>",
    "<form></form>",
    "<label>Name</label>",
    "<input type=\"text\">",
    "<textarea></textarea>",
    "<select></select>",
    "<option>One</option>",
    "<header></header>",
    "<footer></footer>",
    "<main></main>",
    "<nav></nav>",
    "<section></section>",
    "<article></article>",
    "<aside></aside>",
    "<figure></figure>",
    "<figcaption>Cap</figcaption>",
    "<video></video>",
    "<audio></audio>",
    "<source src=\"\">",
    "<link rel=\"stylesheet\">",
    "<style></style>",
    "<script></script>",
    "<title>Page</title>",
    "<body></body>",
    "<head></head>",
    "<html></html>",
    "<div class=\"box\"></div>",
    "<p id=\"intro\"></p>",
    "<img src=\"logo.png\" alt=\"Logo\">",
    "<button type=\"button\">OK</button>",
    "<input type=\"email\">",
    "<input type=\"password\">",
    "<input type=\"checkbox\">",
    "<input type=\"radio\">",
    "<input type=\"hidden\">",
    "<input type=\"submit\">",
    "<meta name=\"viewport\">",
    "<base href=\"/\">",
    "<abbr title=\"HTML\">HTML</abbr>",
    "<cite>Source</cite>",
    "<small>Note</small>",
    "<sub>2</sub>",
    "<sup>2</sup>",
    "<mark>Highlight</mark>",
    "<del>Removed</del>",
    "<ins>Added</ins>",
    "<blockquote>Quote</blockquote>",
    "<q>Short quote</q>",
    "<dl></dl>",
    "<dt>Term</dt>",
    "<dd>Def</dd>",
    "<details></details>",
    "<summary>More</summary>",
    "<dialog></dialog>",
    "<canvas></canvas>",
    "<svg></svg>",
    "<template></template>",
    "<slot></slot>",
    "<wbr>",
    "<!-- comment -->",
    "<noscript></noscript>",
    "<iframe></iframe>",
    "<embed>",
    "<object></object>",
    "<param name=\"x\">",
    "<map name=\"map\"></map>",
    "<area alt=\"\">",
    "<colgroup></colgroup>",
    "<col>",
    "<caption>Table</caption>",
    "<thead></thead>",
    "<tbody></tbody>",
    "<tfoot></tfoot>",
    "<fieldset></fieldset>",
    "<legend>Group</legend>",
    "<datalist></datalist>",
    "<output></output>",
    "<meter value=\"0.5\">",
    "<progress value=\"50\">",
    "<main></main>",
    "<nav></nav>",
    "<section></section>",
    "<article></article>",
    "<p class=\"text\"></p>",
    "<div id=\"root\"></div>",
    "<span class=\"badge\">New</span>",
    "<a href=\"/\">Home</a>",
    "<a href=\"/about\">About</a>",
    "<img src=\"/logo.svg\" alt=\"\">",
    "<button type=\"button\">Save</button>",
    "<button disabled>Wait</button>",
    "<input type=\"text\" name=\"q\">",
    "<input type=\"number\" min=\"0\">",
    "<input type=\"date\">",
    "<input type=\"file\" accept=\"image/*\">",
    "<textarea rows=\"4\" cols=\"40\"></textarea>",
    "<select name=\"size\"><option>S</option></select>",
    "<label for=\"email\">Email</label>",
    "<form action=\"/api\" method=\"post\"></form>",
    "<table border=\"1\"></table>",
    "<thead><tr><th>Name</th></tr></thead>",
    "<tbody><tr><td>Ada</td></tr></tbody>",
    "<ul><li>One</li></ul>",
    "<ol start=\"1\"><li>First</li></ol>",
    "<dl><dt>CPU</dt><dd>Central unit</dd></dl>",
    "<h3>Section</h3>",
    "<h4>Sub</h4>",
    "<hr class=\"divider\">",
    "<br aria-hidden=\"true\">",
    "<strong>Important</strong>",
    "<em>emphasis</em>",
    "<code>npm install</code>",
    "<pre><code></code></pre>",
    "<blockquote cite=\"\">Quote</blockquote>",
    "<figure><img alt=\"\"><figcaption></figcaption></figure>",
    "<video controls src=\"\"></video>",
    "<audio controls src=\"\"></audio>",
    "<source type=\"video/mp4\" src=\"\">",
    "<iframe title=\"\" src=\"\"></iframe>",
    "<canvas width=\"300\" height=\"150\"></canvas>",
    "<svg viewBox=\"0 0 24 24\"></svg>",
    "<link rel=\"icon\" href=\"/favicon.ico\">",
    "<meta charset=\"UTF-8\">",
    "<meta name=\"description\" content=\"\">",
    "<title>App</title>",
    "<style>body{margin:0}</style>",
    "<script defer src=\"/app.js\"></script>",
    "<noscript>Enable JS</noscript>",
    "<template id=\"tpl\"></template>",
    "<slot name=\"icon\"></slot>",
    "<details><summary>FAQ</summary></details>",
    "<dialog open></dialog>",
    "<meter min=\"0\" max=\"100\" value=\"60\"></meter>",
    "<progress max=\"100\" value=\"25\"></progress>",
    "<output for=\"range\"></output>",
    "<fieldset><legend>Account</legend></fieldset>",
    "<datalist id=\"colors\"></datalist>",
    "<optgroup label=\"Group\"></optgroup>",
    "<colgroup span=\"2\"></colgroup>",
    "<caption>Scores</caption>",
    "<wbr>",
    "<!-- TODO: fix -->",
    "<data value=\"\">",
    "<time datetime=\"\">",
    "<mark>",
    "<ruby><rt></rt></ruby>",
    "<bdi>",
    "<bdo dir=\"rtl\">",
    "<s>",
    "<u>",
    "<var>",
    "<samp>",
    "<kbd>",
    "<menu>",
    "<menuitem>",
    "<portal>",
    "<search>",
    "<slot name=\"\">",
  ],
  medium: [
    "<a href=\"https://example.com\" target=\"_blank\">Visit</a>",
    "<input type=\"text\" name=\"email\" required>",
    "<button type=\"submit\" class=\"btn\">Send</button>",
    "<img src=\"/img.png\" alt=\"Photo\" width=\"100\">",
    "<link rel=\"stylesheet\" href=\"style.css\">",
    "<meta charset=\"UTF-8\">",
    "<meta name=\"description\" content=\"App\">",
    "<script src=\"app.js\" defer></script>",
    "<form action=\"/login\" method=\"post\">",
    "<select name=\"country\" id=\"country\">",
    "<textarea name=\"msg\" rows=\"4\" cols=\"40\"></textarea>",
    "<input type=\"number\" min=\"0\" max=\"100\">",
    "<input type=\"date\" name=\"birth\">",
    "<input type=\"file\" accept=\"image/*\">",
    "<label for=\"email\">Email</label>",
    "<div class=\"card\" role=\"region\">",
    "<nav aria-label=\"Main\">",
    "<button aria-expanded=\"false\">Menu</button>",
    "<img loading=\"lazy\" decoding=\"async\" src=\"x.jpg\">",
    "<video controls width=\"640\" height=\"360\">",
    "<audio controls src=\"track.mp3\">",
    "<source src=\"a.webm\" type=\"video/webm\">",
    "<table class=\"data\" border=\"0\">",
    "<th scope=\"col\">Name</th>",
    "<td colspan=\"2\">Value</td>",
    "<tr class=\"row-active\">",
    "<ul class=\"list-none flex gap-2\">",
    "<ol reversed start=\"10\">",
    "<li class=\"item\" data-id=\"1\">",
    "<a rel=\"noopener noreferrer\" href=\"/\">",
    "<input placeholder=\"Search...\" autocomplete=\"off\">",
    "<input type=\"search\" name=\"q\" list=\"suggest\">",
    "<datalist id=\"suggest\"><option value=\"a\"></datalist>",
    "<fieldset disabled><legend>Off</legend></fieldset>",
    "<button formaction=\"/save\" formmethod=\"post\">",
    "<input type=\"reset\" value=\"Clear\">",
    "<input type=\"color\" name=\"theme\">",
    "<input type=\"range\" min=\"0\" max=\"10\" step=\"1\">",
    "<input type=\"tel\" pattern=\"[0-9]{10}\">",
    "<input type=\"url\" placeholder=\"https://\">",
    "<input type=\"time\" name=\"alarm\">",
    "<input type=\"datetime-local\">",
    "<input type=\"month\" name=\"period\">",
    "<input type=\"week\" name=\"week\">",
    "<select multiple size=\"3\" name=\"tags\">",
    "<option value=\"css\" selected>CSS</option>",
    "<optgroup label=\"Languages\">",
    "<details open><summary>FAQ</summary><p>A</p></details>",
    "<dialog open><form method=\"dialog\"></form></dialog>",
    "<template id=\"tpl\"><span></span></template>",
    "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\">",
    "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"none\">",
    "<path d=\"M0 0 L10 10\" stroke=\"currentColor\">",
    "<iframe src=\"/embed\" title=\"Embed\" sandbox=\"\">",
    "<object data=\"file.pdf\" type=\"application/pdf\">",
    "<embed src=\"flash.swf\" type=\"application/x-shockwave-flash\">",
    "<map name=\"imagemap\"><area shape=\"rect\" coords=\"0,0,50,50\"></map>",
    "<picture><source media=\"(min-width:800px)\"><img src=\"\"></picture>",
    "<figure class=\"hero\"><img src=\"\"><figcaption>Hero</figcaption></figure>",
    "<article class=\"post\" lang=\"en\">",
    "<section id=\"features\" aria-labelledby=\"feat-title\">",
    "<header class=\"site-header sticky top-0\">",
    "<footer class=\"site-footer mt-auto\">",
    "<main id=\"content\" tabindex=\"-1\">",
    "<aside class=\"sidebar w-64 shrink-0\">",
    "<div role=\"alert\" aria-live=\"polite\">",
    "<span class=\"badge\" aria-hidden=\"true\">New</span>",
    "<a download href=\"file.zip\">Download</a>",
    "<a href=\"mailto:test@example.com\">Email</a>",
    "<a href=\"tel:+1234567890\">Call</a>",
    "<link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">",
    "<link rel=\"canonical\" href=\"https://example.com/page\">",
    "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">",
    "<meta property=\"og:title\" content=\"Share\">",
    "<meta name=\"twitter:card\" content=\"summary\">",
    "<meta http-equiv=\"refresh\" content=\"30\">",
    "<meta name=\"robots\" content=\"noindex\">",
    "<style media=\"(max-width: 768px)\">",
    "<script type=\"module\" src=\"main.js\"></script>",
    "<script nomodule src=\"legacy.js\"></script>",
    "<base target=\"_blank\">",
    "<colgroup span=\"2\" class=\"cols\">",
    "<caption class=\"sr-only\">Scores</caption>",
    "<input type=\"search\" placeholder=\"Search\" autocomplete=\"off\">",
    "<input type=\"tel\" pattern=\"[0-9]{10}\">",
    "<input type=\"url\" required>",
    "<button type=\"submit\" formaction=\"/save\">Submit</button>",
    "<a href=\"mailto:support@example.com\">Email us</a>",
    "<a href=\"tel:+15551234\">Call</a>",
    "<a download href=\"/file.pdf\">Download</a>",
    "<a target=\"_blank\" rel=\"noopener\">External</a>",
    "<img srcset=\"a.jpg 1x, b.jpg 2x\" sizes=\"100vw\" alt=\"\">",
    "<picture><source media=\"(min-width:800px)\" srcset=\"\"><img alt=\"\"></picture>",
    "<video poster=\"thumb.jpg\" preload=\"metadata\"></video>",
    "<form enctype=\"multipart/form-data\" method=\"POST\"></form>",
    "<label><input type=\"checkbox\" name=\"agree\"> I agree</label>",
    "<select multiple name=\"tags\"></select>",
    "<textarea maxlength=\"500\"></textarea>",
    "<table role=\"grid\"><thead></thead><tbody></tbody></table>",
    "<th scope=\"col\" abbr=\"Id\">ID</th>",
    "<td colspan=\"2\" rowspan=\"1\">Cell</td>",
    "<nav aria-label=\"Primary\"><ul><li><a href=\"/\">Home</a></li></ul></nav>",
    "<button aria-expanded=\"false\" aria-controls=\"menu\">Menu</button>",
    "<div role=\"alert\" aria-live=\"polite\"></div>",
    "<span aria-hidden=\"true\">*</span>",
    "<main id=\"content\" tabindex=\"-1\"></main>",
    "<section aria-labelledby=\"h-features\"></section>",
    "<article itemscope itemtype=\"https://schema.org/Article\"></article>",
    "<meta property=\"og:title\" content=\"\">",
    "<meta name=\"twitter:card\" content=\"summary\">",
    "<link rel=\"canonical\" href=\"https://example.com/page\">",
    "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">",
    "<script type=\"module\" src=\"/main.js\"></script>",
    "<style>@media (min-width:768px){.nav{display:flex}}</style>",
    "<svg aria-hidden=\"true\" focusable=\"false\"><use href=\"#icon\"></use></svg>",
    "<iframe sandbox=\"allow-scripts\" loading=\"lazy\"></iframe>",
    "<object data=\"file.pdf\" type=\"application/pdf\"></object>",
    "<map name=\"map\"><area shape=\"rect\" coords=\"\" href=\"\"></map>",
    "<input enterkeyhint=\"search\" inputmode=\"search\">",
    "<button popovertarget=\"menu\">",
    "<input type=\"range\" min=\"0\" max=\"100\" step=\"1\">",
    "<meter low=\"0\" high=\"100\" optimum=\"80\">",
  ],
  hard: [
    "<!DOCTYPE html>",
    "<html lang=\"en\">",
    "<head><meta charset=\"UTF-8\"><title>App</title></head>",
    "<body class=\"min-h-screen bg-zinc-900 text-white\">",
    "<article class=\"post\" id=\"main\" itemscope itemtype=\"https://schema.org/BlogPosting\">",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
    "<link rel=\"stylesheet\" href=\"/css/app.css\" crossorigin=\"anonymous\">",
    "<script type=\"module\" src=\"/js/main.js\" crossorigin></script>",
    "<form class=\"grid gap-4\" action=\"/api/submit\" method=\"post\" enctype=\"multipart/form-data\">",
    "<input type=\"email\" name=\"user[email]\" autocomplete=\"email\" required aria-describedby=\"email-hint\">",
    "<button type=\"submit\" class=\"btn btn-primary\" disabled>Submit</button>",
    "<a href=\"/docs\" class=\"inline-flex items-center gap-2\" aria-current=\"page\">Docs</a>",
    "<img srcset=\"small.jpg 480w, large.jpg 800w\" sizes=\"(max-width: 600px) 480px, 800px\" src=\"large.jpg\" alt=\"\">",
    "<video poster=\"thumb.jpg\" preload=\"metadata\" playsinline muted loop autoplay>",
    "<iframe src=\"https://example.com/embed\" allow=\"fullscreen\" referrerpolicy=\"no-referrer\"></iframe>",
    "<svg aria-hidden=\"true\" focusable=\"false\" class=\"icon w-5 h-5\"><use href=\"#icon-check\"></use></svg>",
    "<table role=\"grid\" aria-rowcount=\"10\" aria-colcount=\"5\">",
    "<th scope=\"row\" headers=\"name-col\">Player</th>",
    "<td headers=\"score-col\" aria-sort=\"descending\">100</td>",
    "<select name=\"filters[]\" multiple size=\"5\" aria-label=\"Filter tags\">",
    "<input type=\"checkbox\" name=\"agree\" value=\"1\" checked required id=\"agree\">",
    "<label for=\"agree\"><input id=\"agree\" type=\"checkbox\"> I agree</label>",
    "<fieldset class=\"border p-4 rounded-lg\"><legend class=\"text-sm font-medium\">Account</legend></fieldset>",
    "<details class=\"group\"><summary class=\"cursor-pointer list-none\">Settings</summary><div class=\"mt-2\"></div></details>",
    "<dialog id=\"modal\" class=\"backdrop:bg-black/50 rounded-xl p-6\"><form method=\"dialog\"></form></dialog>",
    "<template id=\"card-tpl\"><article class=\"card p-4 shadow\"></article></template>",
    "<picture><source srcset=\"hero.avif\" type=\"image/avif\"><source media=\"(min-width: 1024px)\" srcset=\"hero-lg.jpg\"><img src=\"hero.jpg\" alt=\"Hero\" fetchpriority=\"high\"></picture>",
    "<nav aria-label=\"Breadcrumb\"><ol><li><a href=\"/\">Home</a></li><li aria-current=\"page\">Test</ol></nav>",
    "<header class=\"flex items-center justify-between px-6 py-4 border-b\"><h1 class=\"text-xl font-bold\">WebType</h1></header>",
    "<main class=\"max-w-3xl mx-auto px-6 py-10\" role=\"main\" id=\"main-content\">",
    "<footer class=\"border-t px-6 py-5 text-xs text-zinc-500\">&copy; 2026 WebType</footer>",
    "<section aria-labelledby=\"section-title\"><h2 id=\"section-title\">Features</h2></section>",
    "<ul role=\"list\" class=\"divide-y divide-white/10\">",
    "<ol type=\"A\" start=\"3\" reversed class=\"list-decimal pl-5\">",
    "<li class=\"flex gap-3\" role=\"listitem\"><span class=\"badge\">1</span><span>First</span></li>",
    "<dl class=\"grid grid-cols-2 gap-x-4\"><dt class=\"font-medium\">WPM</dt><dd>72</dd></dl>",
    "<blockquote cite=\"https://example.com/quote\" class=\"border-l-4 pl-4 italic\">",
    "<pre class=\"overflow-x-auto\"><code class=\"language-html\">&lt;div&gt;&lt;/div&gt;</code></pre>",
    "<meter min=\"0\" max=\"100\" low=\"30\" high=\"70\" optimum=\"90\" value=\"65\">65%</meter>",
    "<progress id=\"load\" max=\"100\" value=\"42\" aria-valuenow=\"42\" aria-valuemax=\"100\">",
    "<output name=\"result\" for=\"a b\">0</output>",
    "<input list=\"browsers\" name=\"browser\" id=\"browser\"><datalist id=\"browsers\"><option value=\"Chrome\"></datalist>",
    "<map name=\"workmap\"><area shape=\"circle\" coords=\"50,50,40\" href=\"sun.htm\" alt=\"Sun\"></map>",
    "<object data=\"chart.svg\" type=\"image/svg+xml\" width=\"300\" height=\"200\"><param name=\"autoplay\" value=\"true\"></object>",
    "<embed src=\"plugin.swf\" width=\"400\" height=\"300\" type=\"application/x-shockwave-flash\">",
    "<noscript><p>Please enable JavaScript to use this app.</p></noscript>",
    "<!--[if IE]><p>Upgrade your browser.</p><![endif]-->",
    "<base href=\"https://cdn.example.com/\" target=\"_blank\">",
    "<link rel=\"manifest\" href=\"/manifest.webmanifest\">",
    "<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\">",
    "<meta name=\"theme-color\" content=\"#0f0f11\" media=\"(prefers-color-scheme: dark)\">",
    "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self'\">",
    "<style>@layer base { html { font-family: system-ui; } }</style>",
    "<script>document.documentElement.dataset.theme = 'dark';</script>",
    "<svg width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M5 12h14\"></path></svg>",
    "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M12 2L2 7v10l10 5 10-5V7L12 2z\">",
    "<circle cx=\"12\" cy=\"12\" r=\"10\" stroke=\"currentColor\" fill=\"transparent\">",
    "<rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\">",
    "<line x1=\"4\" y1=\"20\" x2=\"20\" y2=\"20\" stroke-linecap=\"round\">",
    "<polyline points=\"4 12 8 16 16 8 20 12\" fill=\"none\" stroke=\"currentColor\">",
    "<polygon points=\"12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5\">",
    "<text x=\"12\" y=\"14\" text-anchor=\"middle\" font-size=\"12\">OK</text>",
    "<g transform=\"translate(2,2) scale(0.9)\"><rect width=\"20\" height=\"20\"></g>",
    "<defs><linearGradient id=\"g\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"0%\"></linearGradient></defs>",
    "<use href=\"#icon\" xlink:href=\"#icon\" width=\"24\" height=\"24\">",
    "<foreignObject width=\"100\" height=\"50\"><div xmlns=\"http://www.w3.org/1999/xhtml\"></div></foreignObject>",
    "<article itemprop=\"articleBody\"><h1 itemprop=\"headline\">Title</h1><time datetime=\"2026-05-21\"></time></article>",
    "<input type=\"search\" role=\"searchbox\" aria-label=\"Search site\" enterkeyhint=\"search\">",
    "<button popovertarget=\"menu\" popovertargetaction=\"toggle\" aria-haspopup=\"true\">Menu</button>",
    "<div popover id=\"menu\" class=\"rounded-lg shadow-lg p-4\">",
    "<form><input type=\"hidden\" name=\"_token\" value=\"abc123\"><button formaction=\"/draft\" formnovalidate>Draft</button></form>",
    "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Doc</title></head><body></body></html>",
    "<input list=\"ids\" name=\"id\"><datalist id=\"ids\"><option value=\"a1\"></option></datalist>",
    "<form><input type=\"hidden\" name=\"_token\" value=\"\"><button formaction=\"/draft\" formmethod=\"post\">Draft</button></form>",
    "<dialog id=\"modal\"><form method=\"dialog\"><button>Close</button></form></dialog>",
    "<details name=\"acc\"><summary>One</summary><p>A</p></details>",
    "<template shadowrootmode=\"open\"><style>:host{display:block}</style><slot></slot></template>",
    "<custom-element data-version=\"2\"><span slot=\"label\">Label</span></custom-element>",
    "<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mi>x</mi></math>",
    "<table><caption>Data</caption><colgroup><col span=\"2\"></colgroup><thead><tr><th scope=\"col\">X</th></tr></thead></table>",
    "<video controls muted playsinline loop><source src=\"a.webm\" type=\"video/webm\"></video>",
    "<picture><source type=\"image/avif\" srcset=\"hero.avif\"><img width=\"1200\" height=\"630\" alt=\"Hero\"></picture>",
    "<a href=\"/search?q=test&amp;page=2\">Results</a>",
    "<a href=\"?tab=settings#billing\">Billing</a>",
    "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self'\">",
    "<link rel=\"alternate\" hreflang=\"th\" href=\"/th/\">",
    "<link rel=\"manifest\" href=\"/manifest.webmanifest\">",
    "<script type=\"importmap\">{\"imports\":{\"vue\":\"/vue.js\"}}</script>",
    "<svg viewBox=\"0 0 100 100\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"50\" cy=\"50\" r=\"40\"/></svg>",
    "<form novalidate><input required minlength=\"3\" aria-describedby=\"err\"><span id=\"err\" role=\"alert\"></span></form>",
    "<nav><ol><li><a href=\"/\">Home</a></li><li aria-current=\"page\">Settings</li></ol></nav>",
    "<fieldset disabled><legend>Shipping</legend><input name=\"zip\" autocomplete=\"postal-code\"></fieldset>",
    "<iframe srcdoc=\"<p>Hi</p>\" title=\"Preview\" referrerpolicy=\"no-referrer\"></iframe>",
    "<object type=\"image/svg+xml\" data=\"chart.svg\" width=\"400\" height=\"300\"></object>",
    "<table><tbody><tr><td headers=\"h1 h2\" id=\"c1\">Value</td></tr></tbody></table>",
    "<button popovertarget=\"tip\" popovertargetaction=\"toggle\">?</button><div id=\"tip\" popover>Help</div>",
    "<form><fieldset><legend>Billing</legend><input autocomplete=\"cc-name\" name=\"name\"></fieldset></form>",
  ],
};
