import type { Difficulty } from "../types";

export const JS_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "const x = 1;",
    "let count = 0;",
    "var name = \"\";",
    "return true;",
    "return false;",
    "return null;",
    "return 0;",
    "if (ok) {}",
    "else {}",
    "for (let i = 0; i < n; i++) {}",
    "while (running) {}",
    "break;",
    "continue;",
    "flag = true;",
    "flag = false;",
    "value = null;",
    "let data = undefined;",
    "typeof x === \"string\"",
    "console.log(x);",
    "console.log(\"hi\");",
    "const arr = [];",
    "const obj = {};",
    "arr.push(1);",
    "arr.length",
    "obj.key",
    "obj[\"key\"]",
    "x + 1",
    "a - b",
    "a * b",
    "a / b",
    "a % b",
    "a === b",
    "a !== b",
    "a > b",
    "a < b",
    "a >= b",
    "a <= b",
    "a && b",
    "a || b",
    "!done",
    "fn()",
    "fn(a, b)",
    "Math.max(a, b)",
    "Math.min(a, b)",
    "Math.floor(x)",
    "Number(x)",
    "String(x)",
    "Boolean(x)",
    "parseInt(s, 10)",
    "parseFloat(s)",
    "JSON.stringify(obj)",
    "Date.now()",
    "setTimeout(fn, 100);",
    "clearTimeout(id);",
    "new Date()",
    "new Error(\"msg\")",
    "throw err;",
    "try {} catch (e) {}",
    "class App {}",
    "extends Base",
    "super()",
    "this.x",
    "static method() {}",
    "get value() {}",
    "set value(v) {}",
    "export default App;",
    "export const x = 1;",
    "import App from \"./App\";",
    "const fn = () => {};",
    "const add = (a, b) => a + b;",
    "items.map((x) => x)",
    "items.filter((x) => x)",
    "items.find((x) => x)",
    "items.reduce((a, b) => a + b, 0)",
    "items.forEach((x) => {})",
    "items.includes(x)",
    "items.length",
    "Object.keys(obj)",
    "Object.values(obj)",
    "Object.assign({}, obj)",
    "...items",
    "...obj",
    "`hello ${name}`",
    "'use strict';",
    "// comment",
    "/* block */",
    "let n = 0;",
    "const pi = 3.14;",
    "var legacy = true;",
    "x = 1 + 2;",
    "a && b;",
    "a || b;",
    "!flag;",
    "if (x) return;",
    "else return 0;",
    "for (const x of arr) {}",
    "for (let i = 0; i < n; i++) {}",
    "while (n--) {}",
    "do {} while (false);",
    "switch (k) { case 1: break; }",
    "default: break;",
    "break;",
    "continue;",
    "return;",
    "throw new Error('fail');",
    "try {} catch (e) { console.error(e); }",
    "finally {}",
    "function add(a, b) { return a + b; }",
    "const sub = (a, b) => a - b;",
    "const fn = function() {};",
    "class Point {}",
    "new Point()",
    "extends Array",
    "super();",
    "this.x = 0;",
    "static id = 1;",
    "get area() {}",
    "set value(v) { this._v = v; }",
    "import x from './x';",
    "export { x };",
    "export default fn;",
    "console.log(data);",
    "console.warn('warn');",
    "console.error(err);",
    "debugger;",
    "typeof x === 'number'",
    "Array.isArray(x)",
    "x instanceof Date",
    "null",
    "undefined",
    "NaN",
    "Infinity",
    "Object.keys(o)",
    "Object.values(o)",
    "Object.entries(o)",
    "JSON.parse(s)",
    "JSON.stringify(o)",
    "Math.random()",
    "Math.floor(x)",
    "Date.now()",
    "new Date()",
    "setTimeout(fn, 0);",
    "clearTimeout(id);",
    "setInterval(tick, 1000);",
    "clearInterval(id);",
    "Promise.resolve(1)",
    "async function run() {}",
    "await p;",
    "fetch(url)",
    "localStorage.getItem('k')",
    "sessionStorage.setItem('k', '1');",
    "document.querySelector('.a')",
    "el.textContent = '';",
    "el.classList.add('on');",
    "el.addEventListener('click', fn);",
    "event.preventDefault();",
    "window.location.href = '/';",
    "navigator.userAgent",
    "crypto.getRandomValues(buf);",
    "const x = 1;",
    "let y = 2;",
    "const z = x + y;",
    "foo.bar",
    "arr[0]",
    "obj?.a",
    "fn?.()",
    "a ?? b",
    "a ??= b",
    "a &&= b",
    "a ||= b",
    "delete obj.k",
    "void 0;",
    "in obj",
    "of arr",
    "new Array(3)",
    "new Object()",
    "Array.from({ length: 3 }, (_, i) => i)",
  ],
  medium: [
    "const el = document.getElementById(\"app\");",
    "document.querySelector(\".btn\");",
    "document.querySelectorAll(\"li\");",
    "el.addEventListener(\"click\", fn);",
    "el.classList.add(\"active\");",
    "el.classList.remove(\"hide\");",
    "el.textContent = \"\";",
    "el.setAttribute(\"data-id\", \"1\");",
    "localStorage.getItem(\"key\");",
    "localStorage.setItem(\"key\", val);",
    "sessionStorage.clear();",
    "window.location.href",
    "window.addEventListener(\"resize\", fn);",
    "event.preventDefault();",
    "event.stopPropagation();",
    "const { a, b } = obj;",
    "const [first, ...rest] = arr;",
    "const copy = { ...obj, x: 1 };",
    "const merged = [...a, ...b];",
    "Array.isArray(x)",
    "Array.from(list)",
    "arr.slice(0, 3)",
    "arr.splice(1, 1)",
    "str.includes(\"x\")",
    "str.startsWith(\"/\")",
    "str.endsWith(\".js\")",
    "str.split(\",\")",
    "str.trim()",
    "str.replace(/old/g, \"new\")",
    "Number.isNaN(x)",
    "Number.isFinite(x)",
    "Promise.resolve(1)",
    "Promise.reject(err)",
    "new Promise((resolve) => {})",
    "async function load() {}",
    "await fetch(url)",
    "const res = await fetch(url);",
    "const data = await res.json();",
    "function* gen() {}",
    "yield value;",
    "Symbol(\"id\")",
    "Map",
    "Set",
    "WeakMap",
    "new Map()",
    "map.get(key)",
    "map.set(key, val)",
    "set.has(item)",
    "interface Props { id: string; }",
    "type ID = string | number;",
    "enum Status { Idle, Done }",
    "as const",
    "as HTMLInputElement",
    "instanceof Error",
    "in operator",
    "delete obj.key",
    "void fn()",
    "?? defaultVal",
    "?.optional",
    "obj?.nested?.key",
    "fn?.call(ctx)",
    "a ?? b",
    "a?.b ?? c",
    "import { useState } from \"react\";",
    "const [x, setX] = useState(0);",
    "useEffect(() => {}, []);",
    "useRef(null)",
    "useMemo(() => val, [dep])",
    "useCallback(fn, [dep])",
    "React.createElement(\"div\")",
    "export function Button() {}",
    "export type User = { name: string; };",
    "const [a, b] = [1, 2];",
    "const { id, name } = user;",
    "const copy = { ...obj, id: 2 };",
    "const list = [...a, ...b];",
    "const tpl = `hi ${name}`;",
    "String.raw`line\\n`;",
    "arr.map(x => x * 2)",
    "arr.filter(Boolean)",
    "arr.reduce((s, x) => s + x, 0)",
    "arr.find(x => x.id === id)",
    "arr.some(x => x.ok)",
    "arr.every(x => x > 0)",
    "arr.flatMap(x => x.items)",
    "arr.at(-1)",
    "arr.toSorted((a,b) => a - b)",
    "new Map([[k,v]])",
    "map.get(k)",
    "new Set(list)",
    "set.has(x)",
    "Object.assign({}, defaults, opts)",
    "Object.freeze(obj)",
    "structuredClone(obj)",
    "Symbol('id')",
    "Symbol.for('app')",
    "WeakMap",
    "WeakSet",
    "Proxy target {}",
    "Reflect.get(obj, 'k')",
    "new Error('msg', { cause: err })",
    "Error.captureStackTrace(err)",
    "Promise.all([a,b])",
    "Promise.race([a,b])",
    "Promise.allSettled(tasks)",
    "new Promise((res, rej) => {})",
    "async function* gen() { yield 1; }",
    "for await (const x of stream) {}",
    "AbortController",
    "signal.aborted",
    "Intl.NumberFormat('en').format(n)",
    "Intl.DateTimeFormat().format(d)",
    "queueMicrotask(() => {})",
    "requestAnimationFrame(draw)",
    "performance.now()",
    "import { readFile } from 'node:fs/promises';",
    "import.meta.url",
    "process.env.NODE_ENV",
    "Buffer.from(s, 'utf8')",
    "URL.createObjectURL(blob)",
    "URL.revokeObjectURL(u)",
    "new URL('/path', base)",
    "btoa(s)",
    "atob(s)",
    "encodeURIComponent(s)",
    "const id = Symbol('id');",
    "WeakRef(obj)",
    "FinalizationRegistry(fn)",
    "Atomics.add(i32, 0, 1)",
    "SharedArrayBuffer",
    "WebAssembly.instantiate(bytes)",
  ],
  hard: [
    "const handler = async (e: Event) => { e.preventDefault(); };",
    "export default function Page({ params }: { params: { id: string } }) {}",
    "const schema = z.object({ email: z.string().email() });",
    "const { data, error, isLoading } = useQuery({ queryKey: [\"user\"], queryFn: fetchUser });",
    "useEffect(() => { const ctrl = new AbortController(); return () => ctrl.abort(); }, []);",
    "const debounced = useMemo(() => debounce(fn, 300), [fn]);",
    "interface ApiResponse<T> { data: T; meta: { page: number; }; }",
    "type NonNullable<T> = T extends null | undefined ? never : T;",
    "const entries = Object.entries(obj) as [string, unknown][];",
    "const grouped = arr.reduce<Record<string, Item[]>>((acc, item) => { (acc[item.type] ??= []).push(item); return acc; }, {});",
    "async function* streamLines(path: string) { const file = await open(path); for await (const line of file) yield line; }",
    "const proxy = new Proxy(target, { get(t, k) { return Reflect.get(t, k); } });",
    "class EventEmitter<T extends Record<string, unknown>> { emit<K extends keyof T>(event: K, payload: T[K]) {} }",
    "function assertNever(x: never): never { throw new Error(String(x)); }",
    "const isUser = (v: unknown): v is User => typeof v === \"object\" && v !== null && \"id\" in v;",
    "export const GET = async (req: Request, { params }: { params: { slug: string } }) => { return Response.json({ ok: true }); };",
    "const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { email: \"\" } });",
    "const theme = useContext(ThemeContext) ?? defaultTheme;",
    "const ref = useRef<HTMLTextAreaElement | null>(null);",
    "dispatch({ type: \"SET_USER\", payload: user });",
    "const state = useReducer(reducer, initialState);",
    "const id = useId();",
    "const deferred = useDeferredValue(query);",
    "const transition = useTransition();",
    "const [isPending, startTransition] = useTransition();",
    "startTransition(() => setTab(next));",
    "const memo = useMemo(() => expensive(list), [list]);",
    "const onClick = useCallback((id: string) => () => select(id), [select]);",
    "import type { Metadata } from \"next\";",
    "export const metadata: Metadata = { title: \"App\", description: \"Desc\" };",
    "const cn = (...classes: (string | false | undefined)[]) => classes.filter(Boolean).join(\" \");",
    "const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));",
    "try { await job(); } catch (err) { if (err instanceof ApiError) handle(err); else throw err; }",
    "const ws = new WebSocket(url); ws.onmessage = (e) => onMsg(JSON.parse(e.data));",
    "navigator.clipboard.writeText(text);",
    "crypto.randomUUID()",
    "structuredClone(obj)",
    "queueMicrotask(() => flush());",
    "requestAnimationFrame(() => draw());",
    "cancelAnimationFrame(frameId);",
    "Intl.NumberFormat(\"en\", { style: \"currency\", currency: \"USD\" }).format(n)",
    "new Intl.DateTimeFormat(\"en\", { dateStyle: \"medium\" }).format(d)",
    "const cmp = new Intl.Collator(\"en\").compare;",
    "Array.from({ length: n }, (_, i) => i)",
    "Object.fromEntries(entries)",
    "Object.groupBy(items, (i) => i.type)",
    "const flat = arr.flatMap((x) => x.items)",
    "arr.toSorted((a, b) => a - b)",
    "arr.with(2, value)",
    "const buf = await file.arrayBuffer();",
    "const blob = new Blob([data], { type: \"application/json\" });",
    "const url = URL.createObjectURL(blob);",
    "URL.revokeObjectURL(url);",
    "fetch(url, { method: \"POST\", headers: { \"Content-Type\": \"application/json\" }, body: JSON.stringify(body) })",
    "const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; };",
    "const throttle = (fn, ms) => { let last = 0; return (...a) => { const n = Date.now(); if (n - last >= ms) { last = n; fn(...a); } }; };",
    "function* range(n) { for (let i = 0; i < n; i++) yield i; }",
    "const memoize = (fn) => { const c = new Map(); return (k) => c.has(k) ? c.get(k) : c.set(k, fn(k)).get(k); };",
    "class Emitter { #h = new Map(); on(e, fn) { (this.#h.get(e) ?? this.#h.set(e, []).get(e)).push(fn); } emit(e, d) { this.#h.get(e)?.forEach(fn => fn(d)); } }",
    "const deepMerge = (a, b) => ({ ...a, ...Object.fromEntries(Object.entries(b).map(([k,v]) => [k, v && typeof v === 'object' ? deepMerge(a[k], v) : v])) });",
    "await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });",
    "const res = await fetch(url, { signal: AbortSignal.timeout(5000) }); if (!res.ok) throw new Error(res.statusText);",
    "const ws = new WebSocket(url); ws.onmessage = (e) => onMsg(JSON.parse(e.data));",
    "const worker = new Worker(new URL('./worker.js', import.meta.url), { type: 'module' });",
    "const channel = new MessageChannel(); port1.postMessage({ type: 'init' }, [ transferable ]);",
    "Object.groupBy(items, (i) => i.category)",
    "Map.groupBy(items, (i) => i.type)",
    "const cmp = new Intl.Collator('en', { sensitivity: 'base' }).compare;",
    "Temporal.Now.instant().toString()",
    "using disposer = acquire();",
    "import { Worker, isMainThread, parentPort } from 'node:worker_threads';",
    "const ac = new AbortController(); fetch(url, { signal: ac.signal }); ac.abort();",
    "const stream = ReadableStream.from(async function* () { yield chunk; }());",
    "await Bun.write(path, data);",
    "Deno.readTextFileSync(path);",
    "const pool = new WorkerPool(os.cpus().length); await pool.run(tasks);",
  ],
};
