import type { Difficulty } from "../types";

/** Next.js App Router / backend patterns */
export const NEXT_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "import { NextResponse } from 'next/server'",
    "return NextResponse.json({})",
    "return NextResponse.json({ ok: true })",
    "return new NextResponse('ok')",
    "return NextResponse.redirect('/')",
    "return NextResponse.redirect(url, 302)",
    "NextResponse.next()",
    "NextResponse.rewrite(url)",
    "export async function GET() {}",
    "export async function POST() {}",
    "export async function PUT() {}",
    "export async function DELETE() {}",
    "export async function PATCH() {}",
    "export function GET() {}",
    "export const dynamic = 'force-dynamic'",
    "export const revalidate = 60",
    "export const runtime = 'nodejs'",
    "export const maxDuration = 30",
    "const res = await fetch(url)",
    "await res.json()",
    "await request.json()",
    "await request.text()",
    "request.headers",
    "request.headers.get('authorization')",
    "request.nextUrl",
    "request.nextUrl.searchParams",
    "searchParams.get('q')",
    "new URL(request.url)",
    "cookies().get('token')",
    "cookies().set('token', val)",
    "headers().get('x-forwarded-for')",
    "redirect('/login')",
    "notFound()",
    "unauthorized()",
    "forbidden()",
    "import { redirect } from 'next/navigation'",
    "import { notFound } from 'next/navigation'",
    "import { cookies, headers } from 'next/headers'",
    "params.id",
    "const { id } = await params",
    "export default async function Page() {}",
    "export default function Page() {}",
    "export const metadata = { title: 'App' }",
    "export async function generateMetadata() {}",
    "export async function generateStaticParams() {}",
    "fetch(url, { cache: 'no-store' })",
    "fetch(url, { next: { revalidate: 3600 } })",
    "fetch(url, { next: { tags: ['posts'] } })",
    "revalidatePath('/blog')",
    "revalidateTag('posts')",
    "import { revalidatePath, revalidateTag } from 'next/cache'",
    "'use server'",
    "import { revalidatePath } from 'next/cache'",
    "async function action() { 'use server' }",
    "formData.get('email')",
    "formData.get('name')",
    "use server",
    "import prisma from '@/lib/prisma'",
    "await prisma.user.findMany()",
    "await prisma.post.create({ data: {} })",
    "import { auth } from '@/auth'",
    "const session = await auth()",
    "if (!session) redirect('/login')",
    "import { getServerSession } from 'next-auth'",
    "export const authOptions = {}",
    "NextResponse.json({ error: 'Bad' }, { status: 400 })",
    "status: 201",
    "headers: { 'Content-Type': 'application/json' }",
    "app/api/route.ts",
    "app/api/[id]/route.ts",
    "app/[slug]/page.tsx",
    "layout.tsx",
    "loading.tsx",
    "error.tsx",
    "not-found.tsx",
    "route.ts",
    "page.tsx",
    "middleware.ts",
    "export function middleware(request) {}",
    "NextResponse.next({ request: { headers } })",
    "matcher: ['/dashboard/:path*']",
    "config = { matcher: ['/api/:path*'] }",
    "export async function GET() { return NextResponse.json({ ok: true }); }",
    "const data = await request.json();",
    "redirect('/login');",
    "cookies().get('session');",
    "export async function HEAD() {}",
    "export async function OPTIONS() {}",
    "export const dynamic = 'force-static'",
    "export const runtime = 'edge'",
    "export const preferredRegion = 'auto'",
    "export const maxDuration = 10",
    "const { searchParams } = new URL(request.url)",
    "searchParams.get('page')",
    "headers().get('user-agent')",
    "cookies().set('theme', 'dark')",
    "notFound()",
    "forbidden()",
    "unauthorized()",
    "permanentRedirect('/home')",
    "revalidateTag('products')",
    "unstable_noStore()",
    "connection()",
    "fetch(url, { cache: 'force-cache' })",
    "fetch(url, { next: { revalidate: 60 } })",
    "import prisma from '@/lib/prisma'",
    "await prisma.item.findMany()",
    "const session = await getServerSession(authOptions)",
    "signIn('github')",
    "signOut()",
    "export const metadata = { title: 'App', description: 'Desc' }",
    "export async function generateMetadata({ params }) {}",
    "params.slug",
    "await params",
  ],
  medium: [
    "export async function GET(request: Request, { params }: { params: { id: string } }) {}",
    "export async function GET(_req: Request, ctx: { params: Promise<{ slug: string }> }) { const { slug } = await ctx.params }",
    "const body = await request.json() as CreateInput",
    "const { searchParams } = new URL(request.url)",
    "const page = Number(searchParams.get('page') ?? '1')",
    "return NextResponse.json(data, { status: 200, headers: { 'Cache-Control': 'no-store' } })",
    "return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })",
    "try { const row = await db.query(id) } catch (e) { return NextResponse.json({ error: 'Server error' }, { status: 500 }) }",
    "export async function POST(req: Request) { const session = await auth(); if (!session?.user) return NextResponse.json({ error: 'Auth required' }, { status: 401 }) }",
    "import { z } from 'zod'",
    "const parsed = schema.safeParse(await req.json())",
    "if (!parsed.success) return NextResponse.json(parsed.error.flatten(), { status: 422 })",
    "import { Ratelimit } from '@upstash/ratelimit'",
    "const ip = request.headers.get('x-forwarded-for') ?? '127.0.0.1'",
    "const { success } = await ratelimit.limit(ip)",
    "if (!success) return NextResponse.json({ error: 'Too many requests' }, { status: 429 })",
    "import { Redis } from '@upstash/redis'",
    "await redis.set(`cache:${key}`, data, { ex: 60 })",
    "const cached = await redis.get<Post[]>(key)",
    "import { put } from '@vercel/blob'",
    "const blob = await put(filename, file, { access: 'public' })",
    "import { after } from 'next/server'",
    "after(async () => { await logEvent(id) })",
    "import { connection } from 'next/server'",
    "await connection()",
    "export async function generateStaticParams() { const posts = await getPosts(); return posts.map((p) => ({ slug: p.slug })) }",
    "export const dynamicParams = true",
    "export const fetchCache = 'default-no-store'",
    "import { unstable_cache } from 'next/cache'",
    "const getCached = unstable_cache(async () => fetchStats(), ['stats'], { revalidate: 300, tags: ['stats'] })",
    "import { cache } from 'react'",
    "const getUser = cache(async (id: string) => prisma.user.findUnique({ where: { id } }))",
    "import { draftMode } from 'next/headers'",
    "const { isEnabled } = await draftMode()",
    "draftMode().enable()",
    "import { signIn, signOut } from '@/auth'",
    "await signIn('credentials', formData)",
    "await signOut({ redirectTo: '/' })",
    "import { getToken } from 'next-auth/jwt'",
    "const token = await getToken({ req: request, secret: process.env.AUTH_SECRET })",
    "export async function middleware(request: NextRequest) { const token = await getToken({ req: request }); if (!token) return NextResponse.redirect(new URL('/login', request.url)) }",
    "import type { NextRequest } from 'next/server'",
    "export const config = { matcher: ['/((?!_next|favicon.ico).*)'] }",
    "request.cookies.get('session')?.value",
    "response.cookies.set('theme', 'dark', { httpOnly: true, sameSite: 'lax' })",
    "import { ServerInsertedHTMLContext } from 'next/navigation'",
    "import { createPost } from '@/app/actions/posts'",
    "await createPost(formData)",
    "import { useFormState } from 'react-dom'",
    "import { useFormStatus } from 'react-dom'",
    "export async function createItem(prev: State, formData: FormData) { 'use server' }",
    "redirect(`/posts/${post.id}`)",
    "import { permanentRedirect } from 'next/navigation'",
    "export async function POST(req: Request) { const body = await req.json(); return NextResponse.json(body, { status: 201 }); }",
    "export const revalidate = 60;",
    "'use server';",
    "revalidatePath('/blog');",
    "export async function GET(request: Request) { return NextResponse.json({ ok: true }) }",
    "export async function POST(req: Request) { const body = await req.json(); return NextResponse.json(body, { status: 201 }) }",
    "export async function DELETE(_req: Request, { params }: { params: { id: string } }) {}",
    "const token = request.headers.get('authorization')?.replace('Bearer ', '')",
    "return NextResponse.json({ error: 'Bad request' }, { status: 400 })",
    "return NextResponse.redirect(new URL('/login', request.url))",
    "export async function middleware(request: NextRequest) { return NextResponse.next() }",
    "export const config = { matcher: ['/dashboard/:path*'] }",
    "'use server';",
    "async function createItem(formData: FormData) { 'use server' }",
    "revalidatePath('/posts')",
    "import { unstable_cache } from 'next/cache'",
    "const getData = unstable_cache(async () => fetchData(), ['data'], { revalidate: 300 })",
    "import { cache } from 'react'",
    "const getUser = cache(async (id: string) => loadUser(id))",
    "draftMode().enable()",
    "const { isEnabled } = await draftMode()",
    "import { after } from 'next/server'",
    "after(() => log())",
    "import { put } from '@vercel/blob'",
    "const blob = await put(path, file, { access: 'public' })",
  ],
  hard: [
    "export async function GET(request: NextRequest, segmentData: { params: Promise<{ tenantId: string; resourceId: string }> }) { const { tenantId, resourceId } = await segmentData.params; const session = await auth(); if (!session?.user || !canAccess(session.user, tenantId)) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const item = await prisma.resource.findFirst({ where: { id: resourceId, tenantId } }); if (!item) return NextResponse.json({ error: 'Not found' }, { status: 404 }); return NextResponse.json(item) }",
    "export async function POST(request: Request) { const idempotencyKey = request.headers.get('Idempotency-Key'); if (idempotencyKey) { const existing = await redis.get(`idem:${idempotencyKey}`); if (existing) return NextResponse.json(JSON.parse(existing)) } const body = createSchema.parse(await request.json()); const created = await prisma.$transaction(async (tx) => { const row = await tx.order.create({ data: body }); await tx.outbox.create({ data: { type: 'order.created', payload: row.id } }); return row }); if (idempotencyKey) await redis.set(`idem:${idempotencyKey}`, JSON.stringify(created), { ex: 86400 }); return NextResponse.json(created, { status: 201 }) }",
    "import { waitUntil } from '@vercel/functions'",
    "export async function POST(req: Request) { const job = await enqueue(await req.json()); waitUntil(trackJob(job.id)); return NextResponse.json({ jobId: job.id }, { status: 202 }) }",
    "export const runtime = 'edge'",
    "export async function GET() { const geo = (await headers()).get('x-vercel-ip-country') ?? 'US'; return NextResponse.json({ geo }) }",
    "import { OpenAIStream, StreamingTextResponse } from 'ai'",
    "export async function POST(req: Request) { const { messages } = await req.json(); const stream = await openai.chat.completions.create({ model: 'gpt-4o-mini', messages, stream: true }); return new StreamingTextResponse(OpenAIStream(stream)) }",
    "import { auth } from '@/lib/auth'",
    "export const { handlers: { GET, POST }, auth, signIn, signOut } = NextAuth({ providers: [GitHub, Google], callbacks: { session({ session, token }) { session.user.id = token.sub!; return session } } })",
    "export async function middleware(request: NextRequest) { const pathname = request.nextUrl.pathname; const isApi = pathname.startsWith('/api'); const session = await auth(); if (pathname.startsWith('/admin') && session?.user?.role !== 'admin') return NextResponse.redirect(new URL('/403', request.url)); const res = NextResponse.next(); res.headers.set('x-pathname', pathname); return res }",
    "export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = await getPost(slug); if (!post) return {}; return { title: post.title, openGraph: { images: [post.cover] } } }",
    "export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ tab?: string }> }) { const [{ id }, sp] = await Promise.all([params, searchParams]); const data = await getDashboard(id, sp.tab ?? 'overview'); return <Dashboard data={data} /> }",
    "const stream = new ReadableStream({ async start(controller) { for await (const chunk of generator()) controller.enqueue(encoder.encode(chunk)); controller.close() } })",
    "return new Response(stream, { headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' } })",
    "import { Webhook } from 'svix'",
    "export async function POST(req: Request) { const payload = await req.text(); const wh = new Webhook(process.env.CLERK_WEBHOOK_SECRET!); const evt = wh.verify(payload, Object.fromEntries(req.headers)) as Event; await handleWebhook(evt); return NextResponse.json({ received: true }) }",
    "import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'",
    "const supabase = createRouteHandlerClient({ cookies })",
    "export async function GET() { const { data: { session } } = await supabase.auth.getSession(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) }",
    "export async function registerRoutes() { app.get('/health', () => ({ ok: true })); }",
    "import { withAuth } from '@/lib/api/with-auth'",
    "export const GET = withAuth(async ({ user, request }) => { const items = await listForUser(user.id); return NextResponse.json({ items }) })",
    "export async function OPTIONS() { return new NextResponse(null, { status: 204, headers: { 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type, Authorization' } }) }",
    "import { captureException } from '@sentry/nextjs'",
    "export async function GET() { try { return NextResponse.json(await load()) } catch (error) { captureException(error); return NextResponse.json({ error: 'Internal error' }, { status: 500 }) } }",
    "export const preferredRegion = ['iad1', 'sfo1']",
    "export const dynamic = 'force-static'",
    "export const revalidate = false",
    "import { serialize } from 'cookie'",
    "response.headers.append('Set-Cookie', serialize('sid', token, { httpOnly: true, secure: true, path: '/', sameSite: 'strict' }))",
    "export async function GET(request: NextRequest) { const token = request.headers.get('authorization'); if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); }",
    "export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; return { title: slug }; }",
    "export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) { const { id } = await ctx.params; const row = await db.find(id); if (!row) return NextResponse.json({ error: 'Not found' }, { status: 404 }); return NextResponse.json(row) }",
    "export async function POST(request: Request) { const ip = request.headers.get('x-forwarded-for') ?? '127.0.0.1'; const { success } = await ratelimit.limit(ip); if (!success) return NextResponse.json({ error: 'Rate limited' }, { status: 429 }); const body = schema.parse(await request.json()); return NextResponse.json(await create(body), { status: 201 }) }",
    "export async function middleware(request: NextRequest) { const session = await auth(); if (!session && request.nextUrl.pathname.startsWith('/app')) return NextResponse.redirect(new URL('/login', request.url)); return NextResponse.next() }",
    "export default async function Page({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ q?: string }> }) { const [{ slug }, sp] = await Promise.all([params, searchParams]); return <View slug={slug} q={sp.q} /> }",
    "export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = await getPost(slug); return { title: post?.title, openGraph: { images: [post?.image ?? '/og.png'] } } }",
    "export const { GET, POST } = handlers",
    "export const runtime = 'nodejs'",
    "export const dynamic = 'force-dynamic'",
  ],
};
