import type { Difficulty } from "../types";

export const REACT_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "import React from \"react\";",
    "import { useState } from \"react\";",
    "export default function App() {}",
    "function App() { return null; }",
    "const App = () => null;",
    "return <div />;",
    "return <></>;",
    "return null;",
    "return true;",
    "return false;",
    "<div />",
    "<span />",
    "<p>Hello</p>",
    "<button>Click</button>",
    "<input />",
    "<img src=\"\" alt=\"\" />",
    "<a href=\"/\">Link</a>",
    "<ul><li /></ul>",
    "<h1>Title</h1>",
    "className=\"\"",
    "className=\"flex\"",
    "className=\"p-4\"",
    "id=\"app\"",
    "key={id}",
    "ref={ref}",
    "onClick={fn}",
    "onChange={fn}",
    "onSubmit={fn}",
    "disabled={false}",
    "hidden={true}",
    "aria-label=\"Close\"",
    "role=\"button\"",
    "type=\"button\"",
    "value={value}",
    "defaultValue=\"\"",
    "placeholder=\"Search\"",
    "children",
    "props.children",
    "{children}",
    "{value}",
    "{count}",
    "{isOpen && <Modal />}",
    "{list.map((item) => <li key={item.id} />)}",
    "const [x, setX] = useState(0);",
    "const [open, setOpen] = useState(false);",
    "const [text, setText] = useState(\"\");",
    "setX(x + 1);",
    "setOpen(true);",
    "setOpen(false);",
    "useEffect(() => {}, []);",
    "useEffect(() => { fn(); }, [dep]);",
    "useRef(null);",
    "const ref = useRef<HTMLDivElement>(null);",
    "useMemo(() => value, [dep]);",
    "useCallback(() => {}, []);",
    "React.Fragment",
    "<React.Fragment />",
    "export { Button };",
    "export type Props = { id: string; };",
    "interface Props { name: string; }",
    "type Props = { count: number; };",
    "function Button({ label }: { label: string }) {}",
    "const Button = ({ label }: Props) => <button>{label}</button>;",
    "props.label",
    "props.onClick",
    "spread {...props}",
    "<Component {...props} />",
    "<Slot />",
    "createContext(null)",
    "useContext(Ctx)",
    "Provider value={value}",
    "<Provider>{children}</Provider>",
    "forwardRef(fn)",
    "memo(Component)",
    "lazy(() => import(\"./Page\"))",
    "Suspense fallback={<Spinner />}",
    "<Suspense><Page /></Suspense>",
    "StrictMode",
    "createRoot(el)",
    "render(<App />, el)",
    "hydrateRoot(el, <App />)",
    "useId()",
    "useReducer(reducer, init)",
    "dispatch({ type: \"inc\" })",
    "useLayoutEffect(() => {}, []);",
    "useImperativeHandle(ref, () => ({}))",
    "cloneElement(child, { className })",
    "Children.map(children, fn)",
    "isValidElement(node)",
    "key={uuid()}",
    "data-testid=\"btn\"",
    "style={{ color: \"red\" }}",
    "dangerouslySetInnerHTML={{ __html: html }}",
    "import React from 'react';",
    "export default function App() { return <div />; }",
    "<button onClick={() => setOpen(true)}>Open</button>",
    "<input value={text} onChange={onChange} />",
    "const [count, setCount] = useState(0);",
    "useEffect(() => {}, []);",
    "useRef(null);",
    "<div className=\"flex gap-2\">",
    "<p className=\"text-sm text-muted\">",
    "{items.map(i => <li key={i.id} />)}",
    "{show && <Modal onClose={() => setShow(false)} />}",
    "<Link href=\"/about\">About</Link>",
    "children",
    "props.title",
    "spread {...rest}",
    "<Component as=\"section\" />",
    "<div className=\"container\">",
    "<span className=\"sr-only\">",
    "<button disabled={loading}>",
    "<input readOnly />",
    "<textarea rows={4} />",
    "<select defaultValue=\"\">",
    "<form onSubmit={handleSubmit}>",
    "<label htmlFor=\"email\">",
    "<img alt=\"\" src={src} />",
    "<a href={url} target=\"_blank\" rel=\"noreferrer\">",
    "<ul role=\"list\">",
    "<li role=\"listitem\">",
    "useState(false)",
    "useState<string>('')",
    "useState<number | null>(null)",
    "useReducer(reducer, init)",
    "useContext(Ctx)",
    "useId()",
    "useDeferredValue(q)",
    "useTransition()",
    "useRef<HTMLDivElement>(null)",
    "useLayoutEffect(() => {}, [])",
    "useImperativeHandle(ref, () => ({}))",
    "useDebugValue(value)",
    "createContext(null)",
    "memo(Component)",
    "lazy(() => import('./X'))",
    "Fragment",
    "<></>",
    "cloneElement(child, props)",
    "Children.map(children, fn)",
    "isValidElement(node)",
    "createElement('div', props)",
    "forwardRef(fn)",
    "displayName = 'X'",
    "propTypes = {}",
    "defaultProps = {}",
    "key={id}",
    "ref={ref}",
    "dangerouslySetInnerHTML={{ __html: html }}",
    "suppressHydrationWarning",
    "aria-label=\"Close\"",
    "aria-hidden={true}",
    "role=\"dialog\"",
    "tabIndex={0}",
    "onKeyDown={onKeyDown}",
    "onFocus={onFocus}",
    "onBlur={onBlur}",
    "className={cn(base, active && 'on')}",
    "style={{ color: 'red' }}",
    "data-testid=\"btn\"",
    "data-state=\"open\"",
    "title=\"Tip\"",
  ],
  medium: [
    "\"use client\";",
    "import { useState, useEffect } from \"react\";",
    "import Link from \"next/link\";",
    "import Image from \"next/image\";",
    "export default function Page() { return <main />; }",
    "export function Layout({ children }: { children: React.ReactNode }) {}",
    "const [state, setState] = useState<{ open: boolean }>({ open: false });",
    "useEffect(() => { const t = setTimeout(fn, 300); return () => clearTimeout(t); }, []);",
    "useEffect(() => { document.title = title; }, [title]);",
    "const handler = (e: React.MouseEvent) => { e.preventDefault(); };",
    "const onChange = (e: React.ChangeEvent<HTMLInputElement>) => setText(e.target.value);",
    "const onKeyDown = (e: React.KeyboardEvent) => { if (e.key === \"Enter\") submit(); };",
    "ref={inputRef}",
    "tabIndex={0}",
    "autoFocus",
    "readOnly",
    "required",
    "name=\"email\"",
    "htmlFor=\"email\"",
    "<label htmlFor=\"email\">Email</label>",
    "<form onSubmit={handleSubmit}>",
    "<button type=\"submit\" disabled={loading}>",
    "{loading ? <Spinner /> : \"Save\"}",
    "{error && <p className=\"text-red-500\">{error}</p>}",
    "className={cn(\"btn\", isActive && \"btn-active\")}",
    "className={clsx(base, variant)}",
    "variants={{ hidden: { opacity: 0 }, show: { opacity: 1 } }}",
    "initial=\"hidden\"",
    "animate=\"show\"",
    "whileHover={{ scale: 1.02 }}",
    "whileTap={{ scale: 0.98 }}",
    "transition={{ duration: 0.2 }}",
    "layoutId=\"active\"",
    "AnimatePresence mode=\"wait\"",
    "<motion.div layout />",
    "useSearchParams()",
    "usePathname()",
    "useRouter()",
    "router.push(\"/dashboard\")",
    "redirect(\"/login\")",
    "notFound()",
    "generateMetadata({ params })",
    "export const metadata = { title: \"App\" };",
    "dynamic = \"force-dynamic\"",
    "revalidate = 60",
    "fetch(url, { cache: \"no-store\" })",
    "const data = await getData();",
    "async function Page() {}",
    "Promise.all([getUser(), getPosts()])",
    "ErrorBoundary",
    "componentDidCatch(error, info)",
    "getDerivedStateFromError(error)",
    "useErrorBoundary()",
    "createPortal(children, document.body)",
    "useSyncExternalStore(subscribe, getSnapshot)",
    "useInsertionEffect(() => {}, []);",
    "useDeferredValue(query)",
    "useTransition()",
    "startTransition(() => setTab(t));",
    "const deferred = useDeferredValue(value);",
    "useOptimistic(state, reducer)",
    "useActionState(action, initial)",
    "formAction={submit}",
    "useFormStatus()",
    "pending={pending}",
    "Server Component",
    "client-only hook",
    "suppressHydrationWarning",
    "typeof window !== \"undefined\"",
    "dynamic(() => import(\"./Chart\"), { ssr: false })",
    "<Image src={src} alt={alt} width={400} height={300} />",
    "<Link href=\"/about\" className=\"link\">About</Link>",
    "params.id",
    "searchParams.q",
    "cookies().get(\"token\")",
    "headers().get(\"x-forwarded-for\")",
    "use(params)",
    "ReactNode",
    "ReactElement",
    "ComponentProps<typeof Button>",
    "PropsWithChildren",
    "RefObject<HTMLInputElement>",
    "MutableRefObject",
    "Dispatch<SetStateAction<number>>",
    "ChangeEventHandler<HTMLInputElement>",
    "\"use client\";",
    "import { useState, useEffect } from 'react';",
    "const onClick = (e: React.MouseEvent<HTMLButtonElement>) => { e.preventDefault(); };",
    "useMemo(() => compute(a, b), [a, b]);",
    "useCallback(() => action(id), [id]);",
    "forwardRef<HTMLInputElement, Props>(function Input(props, ref) { return <input ref={ref} {...props} />; })",
    "<Suspense fallback={<Spinner />}><Page /></Suspense>",
    "dynamic(() => import('./Chart'), { ssr: false })",
    "import Image from 'next/image'",
    "import Link from 'next/link'",
    "import dynamic from 'next/dynamic'",
    "const router = useRouter()",
    "const pathname = usePathname()",
    "const params = useParams()",
    "const searchParams = useSearchParams()",
    "router.push('/dash')",
    "router.replace(url)",
    "router.refresh()",
    "redirect('/login')",
    "notFound()",
    "useSearchParams().get('q')",
    "useFormStatus()",
    "useFormState(action, init)",
    "useOptimistic(state, fn)",
    "useActionState(fn, init)",
    "startTransition(() => setTab(t))",
    "useSyncExternalStore(sub, snap)",
    "useInsertionEffect(() => {}, [])",
    "useEffect(() => { return () => cleanup() }, [dep])",
    "useMemo(() => expensive(n), [n])",
    "useCallback((id: string) => () => select(id), [select])",
    "const Comp = memo(function Comp(p: Props) { return <div /> })",
    "forwardRef<HTMLButtonElement, ButtonProps>(function Button({ className, ...props }, ref) {",
    "createPortal(children, document.body)",
    "hydrateRoot(root, <App />)",
    "createRoot(root).render(<App />)",
    "<ErrorBoundary fallback={<Err />}>{children}</ErrorBoundary>",
    "<Suspense fallback={null}><Lazy /></Suspense>",
    "<AnimatePresence mode=\"wait\">{show && <Panel />}</AnimatePresence>",
    "variants={{ open: { opacity: 1 }, closed: { opacity: 0 } }}",
    "initial=\"closed\" animate=\"open\"",
  ],
  hard: [
    "export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; return <Article slug={slug} />; }",
    "const { data, error, isLoading, refetch } = useQuery({ queryKey: [\"posts\", id], queryFn: () => fetchPost(id), staleTime: 60_000 });",
    "const mutation = useMutation({ mutationFn: updatePost, onSuccess: () => queryClient.invalidateQueries({ queryKey: [\"posts\"] }) });",
    "const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { email: \"\", password: \"\" } });",
    "const watched = useWatch({ control: form.control, name: \"email\" });",
    "const store = create<State>((set) => ({ count: 0, inc: () => set((s) => ({ count: s.count + 1 })) }));",
    "const count = useStore((s) => s.count);",
    "const theme = useContext(ThemeContext) ?? defaultTheme;",
    "const value = useMemo(() => ({ theme, setTheme }), [theme]);",
    "const Comp = forwardRef<HTMLButtonElement, ButtonProps>(({ className, ...props }, ref) => ( <button ref={ref} className={cn(styles, className)} {...props} /> ));",
    "Comp.displayName = \"Button\";",
    "function useMediaQuery(query: string) { const [match, setMatch] = useState(false); useEffect(() => { const m = window.matchMedia(query); setMatch(m.matches); const fn = () => setMatch(m.matches); m.addEventListener(\"change\", fn); return () => m.removeEventListener(\"change\", fn); }, [query]); return match; }",
    "const ref = useRef<HTMLTextAreaElement | null>(null); useEffect(() => { ref.current?.focus(); }, []);",
    "useEffect(() => { const ctrl = new AbortController(); fetch(url, { signal: ctrl.signal }); return () => ctrl.abort(); }, [url]);",
    "const [state, dispatch] = useReducer(reducer, initialState, (init) => ({ ...init, ready: true }));",
    "type Action = { type: \"add\"; payload: Item } | { type: \"remove\"; id: string };",
    "function reducer(state: State, action: Action): State { switch (action.type) { case \"add\": return { ...state, items: [...state.items, action.payload] }; default: return state; } }",
    "export function useControllableState<T>({ value, defaultValue, onChange }: { value?: T; defaultValue: T; onChange?: (v: T) => void }) {}",
    "const Comp = memo(function Comp({ items }: { items: Item[] }) { return <ul>{items.map((i) => <li key={i.id}>{i.name}</li>)}</ul>; }, (a, b) => a.items === b.items);",
    "const Lazy = lazy(() => import(\"./Heavy\").then((m) => ({ default: m.Heavy })));",
    "<ErrorBoundary fallback={<ErrorUI error={error} reset={reset} />}><Suspense fallback={<Skeleton />}><Lazy /></Suspense></ErrorBoundary>",
    "const id = useId(); const descId = `${id}-desc`; <input aria-describedby={descId} /> <p id={descId}>Hint</p>",
    "const [isPending, startTransition] = useTransition(); startTransition(async () => { await save(); router.refresh(); });",
    "useEffect(() => { let cancelled = false; (async () => { const res = await fetch(url); if (!cancelled) setData(await res.json()); })(); return () => { cancelled = true; }; }, [url]);",
    "const debounced = useMemo(() => debounce((v: string) => setQuery(v), 300), []); useEffect(() => () => debounced.cancel(), [debounced]);",
    "const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const q = searchParams.get(\"q\") ?? \"\";",
    "export function Providers({ children }: { children: React.ReactNode }) { return <QueryClientProvider client={queryClient}><ThemeProvider>{children}</ThemeProvider></QueryClientProvider>; }",
    "const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Inputs>();",
    "<input {...register(\"email\", { required: true, pattern: /^[^@]+@[^@]+$/ })} aria-invalid={!!errors.email} />",
    "const field = useFieldArray({ control, name: \"items\" }); field.append({ name: \"\" });",
    "const selected = useSelector((s: RootState) => s.cart.items); const dispatch = useDispatch();",
    "const snap = useSnapshot(store);",
    "const atoms = useAtom(atom);",
    "const [value, setValue] = useAtom(countAtom);",
    "createBrowserRouter([{ path: \"/\", element: <Root />, children: [{ index: true, element: <Home /> }] }])",
    "<Outlet context={{ user }} />",
    "useOutletContext<User>()",
    "useLoaderData() as LoaderData",
    "useActionData()",
    "Form method=\"post\"",
    "navigate(-1)",
    "useBlocker(({ currentLocation, nextLocation }) => isDirty && currentLocation.pathname !== nextLocation.pathname)",
    "ReactDOM.createPortal(<Tooltip />, document.body)",
    "flushSync(() => setState(x));",
    "useLayoutEffect(() => { measure(); }, [items]);",
    "const props = use(propsPromise) as User;",
    "export const dynamic = \"force-static\";",
    "export const revalidate = 0;",
    "export async function generateStaticParams() { return posts.map((p) => ({ slug: p.slug })); }",
    "const session = await auth(); if (!session) redirect(\"/login\");",
    "return <SessionProvider session={session}>{children}</SessionProvider>;",
    "signIn(\"credentials\", { redirect: false, email, password })",
    "const trpc = useTRPC(); const { data } = trpc.user.byId.useQuery({ id });",
    "export default async function Page({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; return <View id={id} />; }",
    "const { data } = useQuery({ queryKey: ['post', id], queryFn: () => fetchPost(id) });",
    "export function Providers({ children }: { children: React.ReactNode }) { return <QueryClientProvider client={qc}>{children}</QueryClientProvider>; }",
    "export default function RootLayout({ children }: { children: React.ReactNode }) { return <html lang=\"en\"><body>{children}</body></html> }",
    "const session = await auth(); if (!session?.user?.id) redirect('/sign-in')",
    "export async function generateStaticParams() { return slugs.map((slug) => ({ slug })) }",
    "const { register, handleSubmit, formState: { errors } } = useForm<FormValues>({ resolver: zodResolver(schema) })",
    "const mutation = useMutation({ mutationFn: updateUser, onSuccess: () => qc.invalidateQueries({ queryKey: ['users'] }) })",
    "const store = create<State>()(persist((set) => ({ count: 0, inc: () => set((s) => ({ count: s.count + 1 })) }), { name: 'store' }))",
    "const selected = useSelector((s: RootState) => s.cart.items); const dispatch = useDispatch()",
    "const ref = useRef<HTMLTextAreaElement | null>(null); useEffect(() => { ref.current?.focus() }, [])",
    "useEffect(() => { const ctrl = new AbortController(); fetch(url, { signal: ctrl.signal }); return () => ctrl.abort() }, [url])",
    "function useMediaQuery(query: string) { const [m, setM] = useState(false); useEffect(() => { const mq = window.matchMedia(query); setM(mq.matches); const fn = () => setM(mq.matches); mq.addEventListener('change', fn); return () => mq.removeEventListener('change', fn) }, [query]); return m }",
  ],
};
