import type { Difficulty } from "../types";

export const VUE_SNIPPETS: Record<Difficulty, string[]> = {
  easy: [
    "<template>",
    "</template>",
    "<script setup>",
    "</script>",
    "<style scoped>",
    "</style>",
    "export default {}",
    "defineProps({})",
    "defineEmits([])",
    "defineExpose({})",
    "const props = defineProps()",
    "const emit = defineEmits()",
    "ref(0)",
    "ref(\"\")",
    "ref(null)",
    "const count = ref(0)",
    "const name = ref(\"\")",
    "reactive({})",
    "computed(() => 0)",
    "watch(count, fn)",
    "watchEffect(() => {})",
    "onMounted(() => {})",
    "onUnmounted(() => {})",
    "onUpdated(() => {})",
    "provide(\"key\", val)",
    "inject(\"key\")",
    "toRef(props, \"id\")",
    "toRefs(props)",
    "readonly(state)",
    "shallowRef({})",
    "triggerRef(r)",
    "unref(x)",
    "isRef(x)",
    "nextTick(() => {})",
    "<div />",
    "<p>{{ msg }}</p>",
    "<button @click=\"fn\">",
    "<input v-model=\"text\" />",
    "<img :src=\"url\" />",
    "<a :href=\"link\">",
    "v-if=\"ok\"",
    "v-else",
    "v-show=\"visible\"",
    "v-for=\"item in items\"",
    ":key=\"item.id\"",
    ":class=\"active\"",
    ":style=\"style\"",
    "v-bind=\"attrs\"",
    "v-on:click=\"fn\"",
    "@click=\"fn\"",
    "@submit.prevent",
    "v-model=\"x\"",
    "v-model.number",
    "v-text=\"msg\"",
    "v-html=\"html\"",
    "v-slot:default",
    "#default=\"{ item }\"",
    "<slot />",
    "<slot name=\"header\" />",
    "<component :is=\"tag\" />",
    "<Teleport to=\"body\">",
    "<KeepAlive>",
    "<Suspense>",
    "<Transition>",
    "name=\"fade\"",
    "mode=\"out-in\"",
    "import { ref } from \"vue\"",
    "import { computed, watch } from \"vue\"",
    "createApp(App)",
    "app.mount(\"#app\")",
    "app.use(router)",
    "app.use(pinia)",
    "const store = useStore()",
    "store.count",
    "store.$patch({})",
    "pinia.defineStore(\"id\", {})",
    "useRoute()",
    "useRouter()",
    "router.push(\"/\")",
    "router.replace(path)",
    "route.params.id",
    "route.query.q",
    "const count = ref(0);",
    "<template><div /></template>",
    "v-if=\"ok\"",
    "v-for=\"n in 10\" :key=\"n\"",
    "@click=\"submit\"",
    "v-model=\"email\"",
    "import { ref, computed } from 'vue';",
    "defineProps<{ id: string }>()",
    "const msg = ref('')",
    "const list = ref([])",
    "const user = reactive({ name: '' })",
    "computed(() => list.value.length)",
    "watch(msg, (v) => {})",
    "watchEffect(() => {})",
    "onMounted(() => {})",
    "onUnmounted(() => {})",
    "onBeforeMount(() => {})",
    "provide('key', val)",
    "inject('key')",
    "toRef(state, 'x')",
    "toRefs(props)",
    "readonly(state)",
    "shallowRef({})",
    "triggerRef(r)",
    "customRef(() => ({}))",
    "nextTick(() => {})",
    "defineComponent({})",
    "h('div', {}, [])",
    "resolveComponent('X')",
    "<template><slot /></template>",
    "<template #default>",
    "<template v-slot:item=\"{ row }\">",
    "v-else-if=\"err\"",
    "v-else",
    "v-show=\"open\"",
    "v-once",
    "v-pre",
    "v-memo=\"[id]\"",
    "v-bind=\"$attrs\"",
    "v-bind:id",
    ":disabled=\"busy\"",
    ":class=\"cls\"",
    "@click.prevent",
    "@submit.stop",
    "@keyup.enter=\"submit\"",
    "v-model.trim",
    "v-model.number",
    "v-model.lazy",
    "import { ref, computed } from 'vue'",
    "createApp(App).mount('#app')",
  ],
  medium: [
    "const props = defineProps<{ id: string }>()",
    "const emit = defineEmits<{ (e: \"save\", v: string): void }>()",
    "defineModel<string>()",
    "const model = defineModel()",
    "watch(() => props.id, async (id) => {})",
    "watch([a, b], ([na, nb]) => {})",
    "watchEffect(async () => {})",
    "computed({ get() {}, set(v) {} })",
    "shallowReactive({ list: [] })",
    "markRaw(obj)",
    "toRaw(state)",
    "customRef((track, trigger) => ({}))",
    "onBeforeMount(() => {})",
    "onBeforeUnmount(() => {})",
    "onErrorCaptured((err) => false)",
    "onActivated(() => {})",
    "onDeactivated(() => {})",
    "<script setup lang=\"ts\">",
    "<style scoped lang=\"scss\">",
    "v-for=\"(item, i) in items\" :key=\"item.id\"",
    "v-memo=\"[item.id, item.done]\"",
    ":class=\"{ active: isActive }\"",
    ":class=\"[base, isActive && 'on']\"",
    "@click.stop",
    "@click.once",
    "@keyup.enter",
    "v-model.trim",
    "v-model.lazy",
    "v-model:count=\"n\"",
    "<RouterView />",
    "<RouterLink :to=\"{ name: 'home' }\">",
    "<KeepAlive include=\"List\" />",
    "<Suspense><Async /><template #fallback><Spinner /></template></Suspense>",
    "defineAsyncComponent(() => import('./Modal.vue'))",
    "const Async = defineAsyncComponent(loader)",
    "useAttrs()",
    "useSlots()",
    "withDefaults(defineProps<Props>(), { size: 'md' })",
    "defineOptions({ name: 'Card' })",
    "<template #item=\"{ row }\">{{ row.name }}</template>",
    "v-pre",
    "v-once",
    "v-cloak",
    "createRouter({ history: createWebHistory(), routes })",
    "createPinia()",
    "storeToRefs(store)",
    "mapState(useStore, ['count'])",
    "const { data } = await useFetch('/api')",
    "useHead({ title: 'Page' })",
    "useSeoMeta({ title: 'App' })",
    "onServerPrefetch(async () => {})",
    "import.meta.env.VITE_API_URL",
    "<NuxtLink to=\"/about\" />",
    "navigateTo('/login')",
    "useAsyncData('key', () => $fetch('/api'))",
    "useState('count', () => 0)",
    "definePageMeta({ layout: 'admin' })",
    "<script setup lang=\"ts\">",
    "const emit = defineEmits<{ save: [id: string] }>();",
    "watchEffect(() => {});",
    "const route = useRoute();",
    "router.push({ name: 'home' });",
    "defineAsyncComponent(() => import('./Modal.vue'))",
    "defineProps<{ id: string; label?: string }>()",
    "defineEmits<{ (e: 'update', v: string): void }>()",
    "withDefaults(defineProps<Props>(), { size: 'md' })",
    "defineExpose({ focus })",
    "defineOptions({ name: 'Card' })",
    "defineSlots<{ default(): void }>()",
    "defineModel<string>()",
    "const model = defineModel('count', { type: Number })",
    "watch(() => route.params.id, fetch)",
    "watch([a, b], ([na, nb]) => {})",
    "watchEffect(async () => { await load() })",
    "onScopeDispose(() => {})",
    "effectScope(() => {})",
    "getCurrentInstance()",
    "useAttrs()",
    "useSlots()",
    "createRouter({ history: createWebHistory(), routes })",
    "useRoute()",
    "useRouter()",
    "createPinia()",
    "defineStore('cart', { state: () => ({ items: [] }) })",
    "storeToRefs(store)",
    "const { data } = await useFetch('/api')",
    "defineAsyncComponent(() => import('./Modal.vue'))",
    "<RouterView />",
    "<RouterLink :to=\"{ name: 'home' }\">",
    "<KeepAlive><Page /></KeepAlive>",
    "<Teleport to=\"body\"><Modal /></Teleport>",
    "<Transition name=\"fade\"><Box v-if=\"open\" /></Transition>",
  ],
  hard: [
    "const props = withDefaults(defineProps<{ items: Item[]; dense?: boolean }>(), { dense: false })",
    "const model = defineModel<number>('count', { required: true, default: 0 })",
    "watchEffect(async (onCleanup) => { const sub = subscribe(); onCleanup(() => sub.unsubscribe()) })",
    "const state = reactive({ nested: { list: [] as Item[] } })",
    "const list = computed(() => state.nested.list.filter((i) => i.active))",
    "provide(LocalKey, readonly(state))",
    "const injected = inject<Ref<User>>(UserKey, () => ref(defaultUser), true)",
    "defineComponent({ name: 'List', props: {}, setup(props, { emit, slots, attrs }) { return () => h('ul', slots.default?.()) } })",
    "render(h(App), document.getElementById('app')!)",
    "createSSRApp(App).use(router).mount('#app')",
    "const router = createRouter({ history: createWebHistory(import.meta.env.BASE_URL), routes: [{ path: '/', component: Home }] })",
    "router.beforeEach((to, from, next) => { if (to.meta.auth && !auth.isLoggedIn) next('/login'); else next() })",
    "export const useUserStore = defineStore('user', () => { const user = ref<User | null>(null); const login = async (c: Creds) => { user.value = await api.login(c) }; return { user, login } })",
    "store.$subscribe((mutation, state) => { localStorage.setItem('snap', JSON.stringify(state)) }, { detached: true })",
    "<TransitionGroup name=\"list\" tag=\"ul\"><li v-for=\"item in items\" :key=\"item.id\" /></TransitionGroup>",
    "<Teleport defer to=\"body\"><Modal v-if=\"open\" @close=\"open = false\" /></Teleport>",
    "<Suspense @resolve=\"onReady\"><AsyncPanel /><template #fallback><Skeleton rows=\"4\" /></template></Suspense>",
    "const Comp = defineAsyncComponent({ loader: () => import('./Heavy.vue'), delay: 200, timeout: 10000, suspensible: true })",
    "onServerPrefetch(async () => { await store.fetchUser(route.params.id as string) })",
    "const { data, pending, error, refresh } = await useAsyncData('posts', () => $fetch<Post[]>('/api/posts', { query: { page: 1 } }))",
    "definePageMeta({ middleware: ['auth'], validate: async (route) => /\\d+/.test(route.params.id as string) })",
    "export default defineNuxtConfig({ modules: ['@nuxtjs/tailwindcss'], runtimeConfig: { apiSecret: '', public: { apiBase: '' } } })",
    "export default defineEventHandler(async (event) => { const body = await readBody(event); return { ok: true, body } })",
    "const route = useRoute(); const router = useRouter(); await navigateTo({ path: '/dashboard', query: { tab: 'posts' } })",
    "watch(() => route.fullPath, () => refresh(), { flush: 'post' })",
    "effectScope((scope) => { const local = ref(0); scope.run(() => watch(local, fn)); onScopeDispose(() => scope.stop()) })",
    "customRef<string>((track, trigger) => { let value = ''; return { get() { track(); return value }, set(v) { value = v; trigger() } } })",
    "<script setup lang=\"ts\" generic=\"T extends { id: string }\">",
    "const slots = defineSlots<{ default(props: { item: T }): void; footer(): void }>()",
    "const { data } = await useAsyncData('users', () => $fetch('/api/users'));",
    "definePageMeta({ layout: 'admin' });",
    "export default defineNuxtConfig({ modules: ['@nuxtjs/tailwindcss'] });",
    "const props = defineProps<{ items: Item[]; dense?: boolean }>()",
    "const emit = defineEmits<{ select: [id: string] }>()",
    "const { data, error, refresh } = await useAsyncData('key', () => $fetch('/api/x'))",
    "definePageMeta({ middleware: 'auth', layout: 'dashboard' })",
    "export default defineNuxtPlugin((nuxtApp) => { nuxtApp.provide('hello', (msg: string) => msg) })",
    "const store = defineStore('user', () => { const user = ref<User | null>(null); return { user } })",
    "router.beforeEach((to, from, next) => { if (to.meta.auth && !auth.isLoggedIn) next('/login'); else next() })",
    "<script setup lang=\"ts\" generic=\"T extends { id: string }\">",
  ],
};
